### ISSUE TITLE
[Issue]: Download link not working

### ISSUE THREAD

**Issue by iMrDJAi** [Santroller/Santroller#100]
The download link (https://github.com/sanjay900/SantrollerConfigurator/releases/latest) on the documentations page (https://github.com/sanjay900/SantrollerConfigurator/releases/latest) leads to a non-existing repo.

**Comment by sanjay900** [comment]
which documentations page are you referring to here

**Comment by sanjay900** [comment]
Ah, your looking at the unreleased documentation. That code is not out yet, please use https://sanjay900.github.io/guitar-configurator/

**Comment by sanjay900** [comment]
I have updated the links to make it clear that this firmware is not released yet

**Comment by iMrDJAi** [comment]
@sanjay900 Sorry, I've been referring to https://santroller.tangentmc.net/#download-link. Any ETA for the new firmware tho? I'm interested in using my DualShock 4 controller on my Xbox 360, is that supported by the Guitar Configurator?

**Comment by sanjay900** [comment]
No ETA, I can't actually remember if I supported inputs from PS4 controllers

**Comment by iMrDJAi** [comment]
@sanjay900 I saw an image from https://github.com/Sk1ller1993/J-Runner-with-Extras demonstrating a PS4 controller working on xbox 360, I assume this is Guitar Configurator setup right?

**Comment by sanjay900** [comment]
nope, that would be something totally different.

**Comment by sanjay900** [comment]
Okay i do have support for PS4 controller inputs it seems though

**Comment by iMrDJAi** [comment]
@sanjay900 Alright, I have a PI Pico, I'll experiment with it and let you know if it worked out.

**Comment by sanjay900** [comment]
What exactly do you mean, what can't you find

**Comment by iMrDJAi** [comment]
@sanjay900 PS4 input not shown on list:

![Image](https://github.com/user-attachments/assets/3c93dfc0-9297-4372-914b-613fdef084af)

(Or perhaps it's labeled differently?)

**Comment by sanjay900** [comment]
USB Host input
