### ISSUE TITLE
[Issue] PS2 tilt sensor not triggering correctly on Pi Pico

### ISSUE THREAD

**Issue by rgstoian** [Santroller/Santroller#105]
When using my PS2 guitar in PS2 mode connected to a Pi Pico, the tilt sensor triggers intermittently for very short bursts. It works in Clone Hero, but not in any official games, neither on Windows in XInput mode nor on a PS3 Slim as a GH guitar (tried it in both GH and RB games). I already tried setting the poll rate to 250hz with no success. 

Here's how it looks in the Control Panel, with the guitar standing up straight:

https://github.com/Santroller/Santroller/assets/49798196/e6639a53-69c1-4651-a33e-af043c6483da

The issue does not occur with an Arduino Uno 5V (even though it still blinks on and off, it gets picked up by games):

https://github.com/Santroller/Santroller/assets/49798196/1fc6f92a-d5d5-4552-aa10-9252465eff3d

The issue also does not occur when using queue-based inputs (the tilt axis actually stays solid when triggered), but I'm getting another issue there (on both PS3 and XInput): frets sometimes don't stay pressed when playing sustain notes. Maybe a side effect of needing 100+ fps even on the highest dequeue rate, that's why I'm trying to use it normally.

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
