### ISSUE TITLE
[Issue]: Current version of configurator is not compatible with older versions of macOS 

### ISSUE THREAD

**Issue by Tuna-N-Corn** [Santroller/Santroller#106]
### Please describe your issue.

I tried this configurator on Windows 10 with the Arduino pro micro 5V on a Wiitar and it worked fine. I wanted to try it on a Macbook Air 12" (2015) with MacOs High Sierra on it (no longer supports updates).
Unfortunately the version of Ardwiino configurator available for download is only for MacOs X and I dont know how to compile older releases for my OS.
Pls Help 

### Version

yes

### What operating system are you using?

Mac OS

### os-other

High Sierra

### What microcontroller are you using?

arduino pro micro 5V

### How is your controller programmed?

other issue not controller related or I have not gotten this far

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
