### ISSUE TITLE
[Issue]: Arduino mega 2560 breaks the configurator when connected

### ISSUE THREAD

**Issue by CITRUS-Laim** [Santroller/Santroller#107]
### Please describe your issue.

After write the parameters through the configurator, the Arduino stopped being displayed in it. When reconnect, the program stops responding at this screen:
![image](https://github.com/sanjay900/guitar-configurator/assets/93928949/9e4d493a-6e90-4f59-956a-a98139a40659)
In other programs the guitar is displayed like this, but there is no input:
![image](https://github.com/sanjay900/guitar-configurator/assets/93928949/77e5f25e-6f51-45ba-b629-d489b119c73e)
in dfu mode the arduino is loaded and flashed to this stage:
![image](https://github.com/sanjay900/guitar-configurator/assets/93928949/5b0f06a2-10fb-4448-8a3d-542758d638ea)
There is no com port when connecting a guitar

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

arduino mega 2560

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
