### ISSUE TITLE
[Request]: Rumble Support?

### ISSUE THREAD

**Issue by zagdrath** [Santroller/Santroller#108]
### Please describe your request.

I was just wondering if there was some form of rumble functionality already supported or if there could be one added.

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

arduino uno

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
