### ISSUE TITLE
[Issue]: The tilt function for wii controller guitar as PS3/5 on rb4

### ISSUE THREAD

**Issue by IMRlx** [Santroller/Santroller#109]
### Please describe your issue.

Hi, I recently bought a wii guitar hero blackwiiidow v3 adapter. I had to change the software in the configuration for the controller to work as a ps3 guitar hero. In Hero clone everything works on the computer, but when I tried to play Rock Band 4 on PS5 the controller works except for the tilt function.
In the software the tilt is set to Digital and Pin GP10
What can be changed so that tilt works there too?
thank you

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
