### ISSUE TITLE
[Request]: The ability to remap a certain button to a different button

### ISSUE THREAD

**Issue by JMartinez9820** [Santroller/Santroller#110]
### Please describe your request.

A suggestion I would love to see is the ability to remap buttons on Gamepad mode. Although some games already have an option to remap the buttons, some games don't allow that including the Nintendo Switch Online apps for the NES and SNES. Remapping buttons for games that don't support it would be great because I would love to use my SNES classic edition controllers on my Switch.

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Wii

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
