### ISSUE TITLE
[Issue]: Wii Classic Controller Pro Gamepad mode bumper and triggers are opposite on XInput, X and Y buttons are reversed

### ISSUE THREAD

**Issue by JMartinez9820** [Santroller/Santroller#111]
### Please describe your issue.

The L and R bumpers, and ZL and ZR trigger buttons on the Wii Classic Controller Pro flipped around. L and R correspond to LT and RT, while ZL and ZR are correspond to LB and RB. It should be the other way around where L and R correspond to LB and RB, while ZR and ZR correspond to LT and RT. Although some games allow you to remap certain buttons, it can get slightly annoying when you think you're pressing L or R (LB or RB), but in reality you're pressing LT and RT. I hope this gets fixed in an update because I just played a bit of TMNT Shredder's Revenge with my SNES Classic Edition Controller, and I can't do the ability to find friends. 

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
