### ISSUE TITLE
[Issue]: rockband controller output not working on wii

### ISSUE THREAD

**Issue by NikonUK** [Santroller/Santroller#112]
### Please describe your issue.

im not sure if its even supported but i have set the controller output type to be wii rockband guitar. the device does not show up on my nintendo wii. only doing this so i can replay through rockband on my original wii instead of emulators

### Version

yes

### What operating system are you using?

Other

### os-other

Wii (Homebrewed)

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
