### ISSUE TITLE
Current version of configurator is not compatible with older versions of macOS[Issue]: 

### ISSUE THREAD

**Issue by Tuna-N-Corn** [Santroller/Santroller#113]
### Please describe your issue.

Thanks for the new configurator Sanjay, you are a legend. Still can not run your configurator on macOS High Sierra (10.13.6) it is compatible from macOS Mojave (10.14)
Thanks again for all the work. 

### Version

yes

### What operating system are you using?

Mac OS

### os-other

High Sierra

### What microcontroller are you using?

arduino pro micro 5V

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Sadly as high sierra is end of life, the toolchains i am using don't support it, and its not reasible to downgrade everything to support high sierra. You will need to get a new device sadly.
