### ISSUE TITLE
[Issue]: Crash when importing settings file

### ISSUE THREAD

**Issue by TheNathannator** [Santroller/Santroller#115]
### Please describe your issue.

The Santroller configurator consistently crashes when hitting the `Import Settings from File` button under the Presets dropdown.

![image](https://github.com/Santroller/Santroller/assets/29052821/8b8337d6-fe23-410c-8a03-cd930308ed01)

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

arduino uno

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
This bug has been fixed
