### ISSUE TITLE
[Issue]:Cant download the guitar configurator

### ISSUE THREAD

**Issue by ej9904** [Santroller/Santroller#117]
### Please describe your issue.

goes to download but says file isnt trusted, havent been able to find a way around it.

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

other issue not controller related or I have not gotten this far

**Comment by sanjay900** [comment]
Thats going to be something with your browser, it hasn't been downloaded enough times to make it to the trusted software database but you can always override it.

**Comment by ej9904** [comment]
Hi, sorry if this is intrusive or bothersome but can you tell me how i could overwind it Sent from my iPhoneOn Jan 8, 2024, at 6:27 PM, Sanjay Govind ***@***.***> wrote:﻿
Thats going to be something with your browser, it hasn't been downloaded enough times to make it to the trusted software database but you can always override it.

**Comment by sanjay900** [comment]
what browser are you using?

**Comment by ej9904** [comment]
I figured it out after I emailed you, thank you for responding though, i appreciate the custom service and support, thank youSent from my iPhoneOn Jan 8, 2024, at 7:12 PM, Sanjay Govind ***@***.***> wrote:﻿
what browser are you using?

**Comment by sanjay900** [comment]
fantastic news

**Comment by ej9904** [comment]
How do i hook the guitar up to ps4 rock bandSent from my iPhoneOn Jan 8, 2024, at 7:31 PM, Sanjay Govind ***@***.***> wrote:﻿
fantastic news

**Comment by ej9904** [comment]
Ran into new problems, the guitar can connect now, but the option button wont work, strum wont work.Sent from my iPhoneOn Jan 11, 2024, at 8:17 PM, Sanjay Govind ***@***.***> wrote:﻿
Set the guitar to rock band mode, it should just work on a PS4.

**Comment by sanjay900** [comment]
strum not working is weird, and i presume the options button is the start button so its very odd if that doesnt work. Is this an adapter or a directly wired guitar?

**Comment by ej9904** [comment]
Directly wired controller, i got the solderless kitSent from my iPhoneOn Jan 11, 2024, at 8:40 PM, Sanjay Govind ***@***.***> wrote:﻿
strum not working is weird, and i presume the options button is the start button so its very odd if that doesnt work. Is this an adapter or a directly wired guitar?

**Comment by sanjay900** [comment]
best hitting up the person you brought the kit from, I don't really provide support for kits

**Comment by ej9904** [comment]
Okay thank you for tryingSent from my iPhoneOn Jan 11, 2024, at 8:50 PM, Sanjay Govind ***@***.***> wrote:﻿
best hitting up the person you brought the kit from, I don't really provide support for kits
