### ISSUE TITLE
[Issue]: Attempting to use the USB Breakout with an Xbox Controller crashes program

### ISSUE THREAD

**Issue by debgribz** [Santroller/Santroller#119]
### Please describe your issue.

I am using a Zeroboard v1.1 that is pi pico based, and has a pinout for a USB breakout for controller authentication. No matter what pair of GPIO pins i set D+/- to (they're not numerically marked on the board like a standard Pico), the board disconnects from the Santroller Configurator immediately upon plugging the Xbox controller to that breakout. 

The Xbox controller detects power and acts like it's connected, but the program nor windows detects either the Santroller or the Xbox controller plugged into it. 

### Version

10.0.27

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Contact retrocult, I don't provide support for kits or adapters
