### ISSUE TITLE
[Request]: Allow changing of pins for SCL and SDA for Wii Adapter

### ISSUE THREAD

**Issue by Ham5andw1ch** [Santroller/Santroller#12]
### Please describe your request.

I have a RP2040 compatible board that is missing pins 18 and 19. Can we have a configuration option to change which pins map to SCL and SDA for making a wii adapter?

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Wii

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
