### ISSUE TITLE
[Issue]: Mac OS Application Won't Start

### ISSUE THREAD

**Issue by MarbleMuscle** [Santroller/Santroller#123]
### Please describe your issue.

Mac OS claims the application is "broken" every time I try to open it.

### Version

Latest (also tried the last few

### What operating system are you using?

Mac OS

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
macOS detects the application as damaged as apple requires a developer license to properly sign apps
you can run xattr -r -d com.apple.quarantine /Applications/SantrollerConfigurator.app from a terminal to fix this

**Comment by MarbleMuscle** [comment]
sorry i don't mean to be annoying but how do I do that?

**Comment by sanjay900** [comment]
Open the `terminal` application, and then paste that in

**Comment by MarbleMuscle** [comment]
<img width="569" alt="Screenshot 2024-01-17 at 7 00 42 PM" src="https://github.com/Santroller/Santroller/assets/156972606/c401beba-637a-4a79-bea3-cb9c1c77e83d">

**Comment by MarbleMuscle** [comment]
Not enough arguments for option -d. Expected at least 2 but got 1

usage: xattr [-l] [-r] [-s] [-v] [-x] file [file ...]
       xattr -p [-l] [-r] [-s] [-v] [-x] attr_name file [file ...]
       xattr -w [-r] [-s] [-x] attr_name attr_value file [file ...]
       xattr -d [-r] [-s] attr_name file [file ...]
       xattr -c [-r] [-s] file [file ...]

The first form lists the names of all xattrs on the given file(s).
The second form (-p) prints the value of the xattr attr_name.
The third form (-w) sets the value of the xattr attr_name to the string attr_value.
The fourth form (-d) deletes the xattr attr_name.
The fifth form (-c) deletes (clears) all xattrs.

options:
  -h: print this help
  -l: print long format (attr_name: attr_value and hex output has offsets and
      ascii representation)
  -r: act recursively
  -s: act on the symbolic link itself rather than what the link points to
  -v: also print filename (automatic with -r and with multiple files)
  -x: attr_value is represented as a hex string for input and output

**Comment by sanjay900** [comment]
Where is SantrollerConfigurator.app located at the moment?

**Comment by MarbleMuscle** [comment]
I thought it was in my applications, but now I think its just in my downloads

**Comment by sanjay900** [comment]
youd have to revise that command for wherever the executable is

**Comment by MarbleMuscle** [comment]
YOOO i moved it to my applications, ran the original command again and it worked!!

**Comment by MarbleMuscle** [comment]
thank you so much!!

**Comment by sanjay900** [comment]
no problem! Ill see if i can work out why this is necessary though with a macos vm later
