### ISSUE TITLE
[Issue]: Unable to successfully map tilt

### ISSUE THREAD

**Issue by MarbleMuscle** [Santroller/Santroller#125]
### Please describe your issue.

I'm using a V3 Wii adapter with tilt and I have tried it with every pin available but I must be doing something wrong with the mapping process for making tilt work. Or it just doesn't work on Mac but I don't know why that would be the case when everything else works so well. Let me know if there's a fix. Otherwise, the adapter is working incredibly!

### Version

Latest

### What operating system are you using?

Mac OS

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
Go to retrocults website, there is a tool for his adaptor specifically that binds everything for you.
