### ISSUE TITLE
[Request]: Pro Keys

### ISSUE THREAD

**Issue by Proofeek** [Santroller/Santroller#127]
### Please describe your request.

It would be great if Santroller could emulate Rock Band pro keys, allowing you to play with any USB MIDI keyboard by connecting it through USB host, like this:
![IMG_20240123_180458](https://github.com/Santroller/Santroller/assets/78957574/1c1cd956-8f2e-4c7c-ad23-5d7237f3641b)

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

N/A

**Comment by sanjay900** [comment]
Cool idea but not sure when I'd get to it - midi input is a much more complicated thing than standard controllers

**Comment by Moose1002** [comment]
Some sort of way to replicate a midi pro adapter using Santroller would be awesome! Hope one day you get around to exploring that avenue.

**Comment by sanjay900** [comment]
It's one of those things on the list but I have no idea when it'll happen

**Comment by dude98** [comment]
this could also allow people who have the xbox 360 version of RB3's pro keys to use it on ps3 without buying a wii or ps3 midi pro adapter.
you could probably use RPCS3's midi adapter emulation as a base for figuring out midi support.

**Comment by sanjay900** [comment]
The main problem here is MIDI input and output, which RPCS3 doesn't actually really help with since thats on a USB layer and RPCS3 is much higher than that. I do want to implement it at some point, its just that there are more important things to get working first

**Comment by sanjay900** [comment]
Implemented now
