### ISSUE TITLE
[Issue]: Problem with drum multiplexer

### ISSUE THREAD

**Issue by goku1205** [Santroller/Santroller#128]
### Please describe your issue.

I have a problem setting up a multiplexer for drums. The piezo sensors connected directly to the Raspberry Pico work correctly. However, when using the HP4067 multiplexer on separate channels, when tapping the drums, the buttons act as one. It seems like it's not separating the signal into channels.

### Version

v10.0.91

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Did you increase the minimum? This happens if you don't have the sensitivity calibrated correctly, as what your actually seeing is the pads picking up vibrations from the other pads being hit

**Comment by goku1205** [comment]
I changed the minimum values, but the issue persists. It's possible that I made a mistake somewhere in the circuit during the creation. The Santroller project is really great because it breathes new life into my old non-functional drum set and guitar. Below, I'm providing the circuit diagram that I created.
![układ 2](https://github.com/Santroller/Santroller/assets/157888668/14943c57-7442-41cf-a24d-21e7d6b16327)

**Comment by sanjay900** [comment]
Looks right, just keep increasing the minimum even higher 
I presume the resistors are across red and black right?

**Comment by goku1205** [comment]
There is a 1M ohm resistor connected with a red and black wire. I checked today, and when I hit the first piezo, it shows the same value on the second piezo.

**Comment by goku1205** [comment]
![pizo](https://github.com/Santroller/Santroller/assets/157888668/ecb7b409-e988-4716-be6c-05b128e0a303)

**Comment by sanjay900** [comment]
send a copy of `%apppdata%/SantrollerConfigurator/Santroller/include/config_data.h`

**Comment by sanjay900** [comment]
alright nevermind i see the problem
i suspect it will work once you set everything up, the values in the tool are just wrong

**Comment by sanjay900** [comment]
It is just a visual problem though - if you set a decent minimum itll actually work in game, its just not showing correctly in the tool.

**Comment by sanjay900** [comment]
Fixed by v10.0.100
