### ISSUE TITLE
[Issue]: Multiplexer values

### ISSUE THREAD

**Issue by Proofeek** [Santroller/Santroller#135]
### Please describe your issue.

**The values from a multiplexer are different if the pico is reverted to arduino and after saving the settings.**

https://github.com/Santroller/Santroller/assets/78957574/90545e76-00f3-459a-8e96-ac0f3b5ba6a0

1. After reverting to Arduino, the values from the multiplexer seem correct, and each channel takes values only from the corresponding drum. However, after saving, the values change, and the channels take values from any drum (on the video, I hit only the yellow cymbal).

https://github.com/Santroller/Santroller/assets/78957574/8afc5807-09c1-4f0d-ac71-e9f922c8b739

2. After reverting to arduino and pressing Find Pin on any setting, the values from the multiplexer change. This doesn't happen after saving 

### Version

v10.0.113

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Just tested this with my multiplexer, does not seem to be an issue anymore.
