### ISSUE TITLE
[Request]: Several improvements (?)

### ISSUE THREAD

**Issue by Proofeek** [Santroller/Santroller#136]
### Please describe your request.

1.  In Santroller Configurator, it would be better to add the current version number because currently, with the program running, it's impossible to tell. You have to resort to other methods.
2.  It's possible that the link to discord server on the website should be made more prominent. I only found out about the discord server after downloading the tool for the first time.
3. More explanations about what USB Host is and examples of its usage are needed.
4. Images of multiplexers, similar to those in the "Using the tool" section, could be added to the "Wiring a drum kit" section. 
![image](https://github.com/Santroller/Santroller/assets/78957574/d7cc7c9f-7442-464b-9472-e891f1018661)
5. The "Donate Link" and "Current Sponsor" sections on the homepage need to be fixed, something seems to be wrong with them.

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

N/A

### How will the microcontroller be programed for this request?

N/A

**Comment by sanjay900** [comment]
> The "Donate Link" and "Current Sponsor" sections on the homepage need to be fixed, something seems to be wrong with them.
Yeah the docs broke when i was reorganising things, havent gotten around to fixing it yet
