### ISSUE TITLE
[Issue]: linux

### ISSUE THREAD

**Issue by rebornshadow134** [Santroller/Santroller#137]
### Please describe your issue.

installation on Ubuntu 22.04.4 LTS fails every time

### Version

v10.0.126

### What operating system are you using?

Linux

### What microcontroller are you using?

pi pico

### How is your controller programmed?

other issue not controller related or I have not gotten this far

**Comment by sanjay900** [comment]
fails how?

**Comment by rebornshadow134** [comment]
fails to install and says not not supported, using Ubuntu software installer and tried gnome installer same error.

**Comment by sanjay900** [comment]
It is just an executable, set it as executable and run it, there is nothing to install

**Comment by rebornshadow134** [comment]
I've tried just running it as an executable nothing ever loads up

**Comment by sanjay900** [comment]
do you see anything in the console?

**Comment by rebornshadow134** [comment]
no

**Comment by sanjay900** [comment]
unplug your guitar and see if that makes a difference

**Comment by rebornshadow134** [comment]
still nothing, i get spinning mouse but nothing more.

**Comment by sanjay900** [comment]
Im gonna go download a copy of 22.04.4 and see if somethings just broken in that build being that its a daily build and not stable

**Comment by rebornshadow134** [comment]
okay thanks:)

**Comment by sanjay900** [comment]
why are you using 22.04.4 anyways?

**Comment by rebornshadow134** [comment]
for some reason my PC updated earlier when i switched to Ubuntu Pro

**Comment by rebornshadow134** [comment]
i didn't even know that it wasn't stable, its been a hot minute since i used Ubuntu.

**Comment by sanjay900** [comment]
Somehow your on https://cdimage.ubuntu.com/jammy/daily-live/current/ which is 22.04.4
Since https://releases.ubuntu.com/jammy/ is still 22.04.3

**Comment by rebornshadow134** [comment]
reverting back to jammy 22.04.3 ill keep you posted

**Comment by sanjay900** [comment]
sounds good

**Comment by rebornshadow134** [comment]
I did finally get it to work, had to change some settings in console.
