### ISSUE TITLE
[Request]: Is it possible to mod a DJ Hero turntable?

### ISSUE THREAD

**Issue by NaxoDeadAlive** [Santroller/Santroller#14]
### Please describe your request.

Hey, I bought an used DJ Hero turntable without dongle, and i was wondering if is possible to mod it with a Pi Pico

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
