### ISSUE TITLE
PC USB Keyboard to PS4/5

### ISSUE THREAD

**Issue by andrezzz7** [Santroller/Santroller#140]
### Please describe your request.

Hi Sanjay, thanks for the great tool first of all.
Is it possible to connect PC USB keyboard as shown in the image below and configure it as PS3 guitar controller to use it with rock band 4 on PS4/5 
![Capture](https://github.com/Santroller/Santroller/assets/68324921/f9e2f8a6-a042-4c88-a907-40514338867b)

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Not at the moment no, could be possible in the future though.

**Comment by andrezzz7** [comment]
Would be a great feature. I'd imagine to play RB on ps4 using 3 keyboards as we played FoFiX back in the day.
Assume there is something like in the link below that should be implemented to make it possible
https://github.com/vruivo/pico_read_usb_keyboard_pio?tab=readme-ov-file

**Comment by sanjay900** [comment]
There's a lot more to it than that, since I'd have to also support gaming keyboards which use a totally different report format, and I'd have to provide an interface for configuring it as well, but I suspect most of the code I wrote for generic gamepads can help us there

**Comment by sanjay900** [comment]
I already have the code for parsing descriptors anyways so it shouldn't be that difficult

**Comment by sanjay900** [comment]
should be supported with v10.1.46 when it comes out. I am also currently only supporting the boot descriptor but maybe down the track ill support NKRO.
