### ISSUE TITLE
[Issue]: Failure to Write Bluetooth Reciever Settings to Pi Pico W for Rockband Guitars

### ISSUE THREAD

**Issue by Moose1002** [Santroller/Santroller#141]
### Please describe your issue.

Following the guide to creating a bluetooth receiver after all settings have been set and you go to save those settings to the Pi Pico, it creates the following error:

> Processing picow (board: rpipicow; platform: https://github.com/maxgerhardt/platform-raspberrypi/archive/refs/heads/develop.zip; framework: arduino)
> --------------------------------------------------------------------------------
> Verbose mode can be enabled via `-v, --verbose` option
> CONFIGURATION: https://docs.platformio.org/page/boards/raspberrypi/rpipicow.html
> PLATFORM: Raspberry Pi RP2040 (1.11.0) > Pico W
> HARDWARE: RP2040 133MHz, 264KB RAM, 2MB Flash
> DEBUG: Current (cmsis-dap) External (blackmagic, cmsis-dap, jlink, pico-debug, picoprobe, raspberrypi-swd)
> PACKAGES: 
>  - framework-arduinopico @ 1.30200.0 (3.2.0) 
>  - tool-openocd-rp2040-earlephilhower @ 0.0.0 
>  - tool-openocd-rp2040-earlephilhower @ 0.0.0 
>  - tool-rp2040tools @ 1.0.2 
>  - toolchain-rp2040-earlephilhower @ 5.120300.240125 (12.3.0)
> Flash size: 2.00MB
> Sketch size: 2.00MB
> Filesystem size: 0.00MB
> Maximium Sketch size: 2093056 EEPROM start: 0x101ff000 Filesystem start: 0x101ff000 Filesystem end: 0x101ff000
> LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain, Compatibility ~ soft
> Found 49 compatible libraries
> Scanning dependencies...
> Dependency Graph
> |-- USB-Host-Shield-20 @ 1.6.2
> |   |-- SPI @ 1.0
> |-- SPI @ 1.0
> |-- fxpt_math
> Building in release mode
> Compiling .pio/build/picow/src/pico/bt.cpp.o
> Compiling .pio/build/picow/src/pico/bt_rx.cpp.o
> Compiling .pio/build/picow/src/pico/io.cpp.o
> Compiling .pio/build/picow/src/pico/main.cpp.o
> Compiling .pio/build/picow/src/pico/pins.cpp.o
> Compiling .pio/build/picow/src/pico/xinput_device.cpp.o
> Compiling .pio/build/picow/src/pico/xinput_host.cpp.o
> Compiling .pio/build/picow/src/shared/config/config.c.o
> Compiling .pio/build/picow/src/shared/controllers/controllers.c.o
> Compiling .pio/build/picow/src/shared/hid/hid.cpp.o
> Compiling .pio/build/picow/src/shared/main/ps2.cpp.o
> Compiling .pio/build/picow/src/shared/main/shared_main.cpp.o
> Compiling .pio/build/picow/src/shared/main/wii.cpp.o
> Compiling .pio/build/picow/src/shared/usb/descriptors.cpp.o
> Compiling .pio/build/picow/src/shared/usb/string_descriptors.c.o
> Compiling .pio/build/picow/src/shared/usb/xbox.c.o
> src/shared/main/shared_main.cpp: In function 'void convert_universal_to_type(uint8_t*, PCRockBandGuitar_Data_t*, uint8_t)':
> src/shared/main/shared_main.cpp:646:18: error: 'struct PS3RockBandGuitar_Data_t' has no member named 'tiltDigital'
>   646 |             out->tiltDigital = true;
>       |                  ^~~~~~~~~~~
> *** [.pio/build/picow/src/shared/main/shared_main.cpp.o] Error 1

I've tested this also on Windows 11 with version 10.0.152 and the same error occurred so I don't believe it's an OS issue. Would love some insight on this because currently I'm unable to create wireless Rockband Guitars. Thanks!

### Version

10.0.151

### What operating system are you using?

Mac OS

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
v10.0.154 is released now
