### ISSUE TITLE
[Request]: Clarify supported controllers for USB authentication

### ISSUE THREAD

**Issue by Dawwnnn** [Santroller/Santroller#143]
### Please describe your request.

I've wanted to set up USB authentication via the Pi Pico to play on my 360, but I am unsure whether I require a wired 360 controller or if I can just use a wireless one. The documentation does not mention any supported controllers at the moment. 

Cheers!

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Wired controllers only, ill specify that
