### ISSUE TITLE
[Issue]: fails every time i try flash

### ISSUE THREAD

**Issue by NikonUK** [Santroller/Santroller#149]
### Please describe your issue.

if i try to flash the pi pico no matter what it fails. weather its on an earlier version of santroller or latest
![image](https://github.com/Santroller/Santroller/assets/76716629/3dc85e1d-c58f-4728-b848-32ccd3b61c18)
also the "raise issue on github" button redirects to a dead page

### Version

all versions (including latest)

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by NikonUK** [comment]
my current fix is to just use GuitarConfigurator until my pc wants to work with it. it works on my laptop (both linux and windows) so idk

**Comment by sanjay900** [comment]
delete everything from `%appdata%/SantrollerConfigurator` and try again

**Comment by MorleyGarcia** [comment]
I'm having this same issue as well.

**Comment by sanjay900** [comment]
This happening on the initial config, or once you have made changes?

**Comment by sanjay900** [comment]
And when you dismiss this dialog, what does the progress bar say?

**Comment by sanjay900** [comment]
When v10.0.171 comes out, could you please get me the text in that box? hopefully it won't be empty.

**Comment by MorleyGarcia** [comment]
> This happening on the initial config, or once you have made changes?

For me its happening on the initial config, and when I dismiss the dialog the progress bar says that its searching for the device

**Comment by sanjay900** [comment]
@MorleyGarcia v10.0.171 is out now, can you get me the error from  that please?

**Comment by MorleyGarcia** [comment]
This is what I see for the initial config
![image](https://github.com/Santroller/Santroller/assets/55711914/15916017-26a6-45c7-b836-1db86d1b50f4)

And then this is what I see when I dismiss the dialog
![image](https://github.com/Santroller/Santroller/assets/55711914/886e22c9-815c-423c-8220-4c3be7a0a22f)

**Comment by sanjay900** [comment]
How much space is free on your C drive at the moment?

**Comment by sanjay900** [comment]
and whats in the `%appdata%/SantrollerConfigurator/Santroller/.pio/build` directory

**Comment by MorleyGarcia** [comment]
> How much space is free on your C drive at the moment?

I have about 146GB free

> and whats in the `%appdata%/SantrollerConfigurator/Santroller/.pio/build` directory

I don't see a .pio folder in `%appdata%/SantrollerConfigurator/Santroller/ but there is a pio_packages folder with the below contents.

![image](https://github.com/Santroller/Santroller/assets/55711914/24e8f953-ec47-4a49-bbc0-b45f8b489806)

**Comment by sanjay900** [comment]
open a command prompt from `%appdata%/SantrollerConfigurator/Santroller`
and run `../python/python.exe -m platformio run --target upload --environment pico --upload-port D:/` replacing `D:/` with the drive letter from your pico when its in boot mode

**Comment by MorleyGarcia** [comment]
I figured out my issue, so I was using RetroCult Mod's board and I didn't realize he recently updated his firmware for his boards so I had to use his program. 

@NikonUK If by any chance you are using RetroCult's board go to his website and download his program.

**Comment by sanjay900** [comment]
That works since it totally sidesteps the broken bits lol

**Comment by sanjay900** [comment]
Do your PCs potentially have firewalls that are blocking network connections?

**Comment by NikonUK** [comment]
> I figured out my issue, so I was using RetroCult Mod's board and I didn't realize he recently updated his firmware for his boards so I had to use his program.
> 
> @NikonUK If by any chance you are using RetroCult's board go to his website and download his program.

nope. using a raspberry pi pico

also yeah my pcs c drive was full. it works now

**Comment by sanjay900** [comment]
It should have warned you that you don't have enough space, ill have to investigate that.
