### ISSUE TITLE
[Request]: joystick on guitar hero controller type

### ISSUE THREAD

**Issue by NikonUK** [Santroller/Santroller#151]
### Please describe your request.

im unsure if its a bug or hasnt been implemented yet but i am unable to map the guitar hero wii joystick to santroller, i have it soldered correctly and it works fine with guitarconfigurator but i am unable to pick joystick when i am set to type "Guitar Hero Controller"
![image](https://github.com/Santroller/Santroller/assets/76716629/cd34dd8c-bccf-41e9-a01b-0f27896d5d24)

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Wire it to the dpad inputs.
