### ISSUE TITLE
[Issue]: MPR121 not detected

### ISSUE THREAD

**Issue by GrandpaVape** [Santroller/Santroller#154]
### Please describe your issue.

I'm using an official pi pico with one of [these](https://a.co/d/0dMlv03) breakout boards (similar to the discontinued SparkFun variant). Using [Adafruit's CircuitPython example](https://learn.adafruit.com/adafruit-mpr121-12-key-capacitive-touch-sensor-breakout-tutorial/python-circuitpython), I can see the board on address 0x5A responding to touches on all pins.

However, when I use SantrollerConfigurator using the same SDA/SCL pins (GP18/GP19), it doesn't show as detected. I've tried 2 of them already and they work in CircuitPython, but not in Santroller. Any ideas?

### Version

v10.0.186

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Odd, I know my mpr121 breakouts work so I wonder what's different with yours

**Comment by GrandpaVape** [comment]
@sanjay900 Which ones are you using?

**Comment by sanjay900** [comment]
can you throw me the contents of the file `%appdata%/SantrollerConfigurator/Santroller/include/config_data.h`

**Comment by GrandpaVape** [comment]
```
#define CONFIGURATION {0xB,0x1C,0x80,0x10,0x1,0x20,0x1,0x50,0x1,0x58,0x1,0x60,0x5,0x70,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0x1,0xC0,0x1,0xA,0xE8,0x1,0xA,0x8A,0x2,0x0,0x92,0x2,0x0,0xB0,0x2,0x1,0xF8,0x2,0x1,0x80,0x3,0x1F,0x90,0x3,0x1,0x98,0x3,0x5,0xA0,0x3,0x1,0xA8,0x3,0x12,0xB0,0x3,0x13,0x3}
#define CONFIGURATION_LEN 61
#define SWAP_SWITCH_FACE_BUTTONS true
#define WINDOWS_USES_XINPUT true
#define RPCS3_COMPAT false
#define XINPUT_AUTH false
#define INPUT_QUEUE false
#define POLL_RATE 0
#define WT_SENSITIVITY 5
#define INPUT_DJ_TURNTABLE_POLL_RATE 10000
#define INPUT_DJ_TURNTABLE_SMOOTHING false
#define LED_BRIGHTNESS 31
#define ABSOLUTE_MOUSE_COORDS false
#define ARDWIINO_BOARD "pico"
#define EMULATION_TYPE 0
#define DEVICE_TYPE 1
#define USB_HOST_STACK false
#define USB_HOST_DP_PIN -1
#define DIGITAL_COUNT 0
#define LED_COUNT 0
#define LED_COUNT_PERIPHERAL 0
#define LED_COUNT_STP 0
#define LED_COUNT_PERIPHERAL_STP 0
#define ADC_PINS {}
#define ADC_COUNT 0
#define TICK_SHARED \
    
#define TICK_DETECTION \
    
#define TICK_RESET \
    
#define TICK_PS3 \
    
#define TICK_PS3_WITHOUT_CAPTURE \
    
#define TICK_PC \
    
#define TICK_PS4 \
    
#define TICK_XINPUT \
    
#define TICK_XBOX_ONE \
    
#define HANDLE_AUTH_LED \
    
#define HANDLE_PLAYER_LED \
    
#define HANDLE_LIGHTBAR_LED \
    
#define HANDLE_RUMBLE \
    
#define HANDLE_RUMBLE_EXPANDED \
    
#define HANDLE_KEYBOARD_LED \
    
#define PIN_INIT_PERIPHERAL \
    
#define PIN_INIT \
    
#define LED_INIT \
    \
	\
	
#define LED_COUNT_MPR121 0

#define TWI_1_SDA 18
#define TWI_1_SCL 19
#define TWI_1_CLOCK 400000

#define MPR121_TWI_PORT TWI_1
#define MPR121_TOUCHPADS 5
#define MPR121_DDR 0
#define MPR121_ENABLE 0
```

Hmm, MPR121_ENABLE 0 doesn't look correct?

**Comment by sanjay900** [comment]
No thats perfectly fine, thats only for if you are using GPIO inputs

**Comment by sanjay900** [comment]
[firmware.uf2.zip](https://github.com/Santroller/Santroller/files/14712797/firmware.uf2.zip)
try this

**Comment by GrandpaVape** [comment]
![image](https://github.com/Santroller/Santroller/assets/50559874/75c0d5c5-934d-4cae-a4bc-02337eac59d7)
Still not detected

**Comment by sanjay900** [comment]
[firmware.uf2.zip](https://github.com/Santroller/Santroller/files/14715187/firmware.uf2.zip)

**Comment by sanjay900** [comment]
Actually i just looked at your circuit python lib and its literally the code i based my code on haha

**Comment by sanjay900** [comment]
[firmware.uf2.zip](https://github.com/Santroller/Santroller/files/14715211/firmware.uf2.zip)
i noted they have a delay after the soft reset so this has that in it

**Comment by sanjay900** [comment]
[firmware.uf2.zip](https://github.com/Santroller/Santroller/files/14715252/firmware.uf2.zip)
i dropped the i2c frequency

**Comment by sanjay900** [comment]
My breakout looks pretty much identical to yours FYI

**Comment by GrandpaVape** [comment]
yeah still nothing

**Comment by sanjay900** [comment]
you got a second pi pico?

**Comment by GrandpaVape** [comment]
I have one I need to solder some pins to real quick, or I have an [RP2040-Zero](https://a.co/d/exz8G4v) that's ready to go if you can change the pins to one of the available ones. Otherwise gimme like 10 mins to whip out my Pinecil.

FWIW, I first tried this using a [PhunkyCustom's PCB](https://www.etsy.com/listing/1481506753/monoboard-rp-rp2040-integrated-pcb-for) and it wasn't working, but that was before your changes.

**Comment by sanjay900** [comment]
We would be setting up a main pico with the mpr attached
and a second probe pico
probe GP4 -> main GP0
probe GP5 -> main GP1
probe GND -> main GND

**Comment by GrandpaVape** [comment]
oh yeah, I can use the rp2040zero as the probe connected to the Pi Pico. Lemme wire that up rq.

**Comment by sanjay900** [comment]
https://github.com/raspberrypi/debugprobe/releases/download/debugprobe-v2.0/debugprobe_on_pico.uf2
throw this on the probe
[firmware.uf2.zip](https://github.com/Santroller/Santroller/files/14715337/firmware.uf2.zip)
and this on the main

**Comment by sanjay900** [comment]
then you should be able to open a serial terminal using something like putty, point it at the probe and see logs from main

**Comment by GrandpaVape** [comment]
![image](https://github.com/Santroller/Santroller/assets/50559874/52400d06-bbbb-4d9b-a9a2-e7eb9ee548cb)
It looks like I'm getting garbage. Are my settings wrong or does that mean my wiring is bad?

**Comment by GrandpaVape** [comment]
115200, just like u said

**Comment by sanjay900** [comment]
odd, it shouldn't matter what order you plug it in either.

**Comment by GrandpaVape** [comment]
Wait im dumb, lemme check device manager

**Comment by sanjay900** [comment]
Oops, i got the wiring wrong
probe GP4 -> main GP1
probe GP5 -> main GP0

I always forget to flip tx and rx

**Comment by GrandpaVape** [comment]
Ok, so now I get "Console type: 0 | Console type: 9" every time I plug in the main
![image](https://github.com/Santroller/Santroller/assets/50559874/cd1a434d-aa5d-4b48-a747-c5f0eebaee43)

**Comment by sanjay900** [comment]
Oh i think i see the problem
can you actually map an input on your mpr121 to something?

**Comment by GrandpaVape** [comment]
Oh my god was that the problem in the first place :0
![image](https://github.com/Santroller/Santroller/assets/50559874/b3e64879-37dc-46f1-9417-7c73ddbcd94c)

**Comment by sanjay900** [comment]
good stuff haha, ill get that fixed

**Comment by GrandpaVape** [comment]
I had tried binding it to the slider several times before I opened this issue, why didn't that fix it?

**Comment by sanjay900** [comment]
I have no idea, but ill fix it now so that it just works even without it being mapped to anything

**Comment by sanjay900** [comment]
v10.0.188 should have this fixed

**Comment by GrandpaVape** [comment]
You're a king and a legend. Should I close this, or wait to confirm it's fixed with the new version?

**Comment by sanjay900** [comment]
Ill close it now
