### ISSUE TITLE
[Issue]: Wii les paul tilt and back button are swapped?

### ISSUE THREAD

**Issue by flearider** [Santroller/Santroller#155]
### Please describe your issue.

when i try to write my back button it doesn't find the pin half of the time it finds gp16 which is i think the tilt sensors because if i slightly move the guitar it finds it for all the buttons but when i actually try and find the tilt it doesn't work 

### Version

10.0.187

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
Is this a direct wired guitar or a wii adapter
