### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by guitarguy123** [Santroller/Santroller#160]
### Please describe your issue.

 #error missing HID_AXIS_COUNT and HID_BUTTON_COUNT

### Version

v10.0.211

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
can you send a copy of `%appdata%/SantrollerConfigurator/Santroller/include/config_data.h`
The file will only exist at the point where you see the error

**Comment by sanjay900** [comment]
Fixed with v10.0.212
