### ISSUE TITLE
[Request]: Fret matrix support for connecting 5+5 frets over a total of 7 pins

### ISSUE THREAD

**Issue by DragRedSim** [Santroller/Santroller#163]
### Please describe your request.

Looking at the Polybar project, there's been some discussion on their Discord for a way of adding solo frets. As space is obviously limited in one of these controllers, the ability to minimise the number of connections needed is paramount.
As such, I would suggest the following; the ability to configure a set of seven pins in a 5x2 matrix. The 5 side of the matrix should be obvious as GRYBO frets, however the top set would be linked to one of the two pins, as the regular frets, and the bottom set would be linked to the other of the two pins. 
To electronically detect the state of all ten frets, first the main set pin is set to output low, the solo set pin is set to read input, and each of the fret pins are checked for a low state (using pullups on the inputs, as is standard practice). If any main frets are down, they are detected; the solo frets have no bearing as if they are pressed, there is no connection to ground, only to the pulled-up solo set pin. Then the task is performed again, only with the set pins inverted, so that the main set pin is ignored (by having it in input mode), and the solo set is polled in order. 
As I read it, the operational logic for this would be in the TICK_SHARED flow, so it would require changes to what is generated there, as well as to the PIN_INIT to originally switch pins to the required output states.
Unfortunately, since testing the state of a button connected like this is not purely a HIGH/LOW value, it would not be possible to automatically detect the multiple pins required for this connection by simply pressing the button; the setup on the configurator would have to be slightly more involved.

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
I don't see a point of using matrices when we can just use things like MPR121s or peripheral mode to do that sort of thing instead.
