### ISSUE TITLE
[Issue]: Tilt does not work in wireless mode

### ISSUE THREAD

**Issue by XxyZwW** [Santroller/Santroller#164]
### Please describe your issue.

I made a wireless adapter with 2 RPpW, I put an adxl345 in the transmitter and it does not activate the overdrive in rock band 4, I thought it could be an error with the adxl345, I changed it and installed 2 Mercury Ball tilt, low configure in GPIO 16 ( the other pole to gnd) I did the test again and it doesn't activate the overdrive in RB4 either, I tried testing wired and it does activate the overdrive, so I deduce that the problem is only in wireless mode.

### Version

10.0.223

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
interesting i thought i fixed this problem recently but i guess not

**Comment by sanjay900** [comment]
What console are you playing on?

**Comment by XxyZwW** [comment]
On PS4, I made a wireless adapter for Wii guitars

**Comment by sanjay900** [comment]
have you got it in RB or gh mode

**Comment by XxyZwW** [comment]
Estoy emulando guitarra de Guitar Hero

**Comment by sanjay900** [comment]
Can you try the latest release? this might be fixed now

**Comment by XxyZwW** [comment]
Sorry, I hadn't had time to test, but yes, I confirm that yes, the Tilt now works in wireless mode, thank you very much for your work brother.
