### ISSUE TITLE
[Request]: allow letting the ardwiino controller be seen as an xbox one riffmaster controller

### ISSUE THREAD

**Issue by NikonUK** [Santroller/Santroller#166]
### Please describe your request.

i have not got the slightest clue if this will work or is even possible but is there a way you can get the arduino to make the pc think its an xbox one riffmaster controller so we can play guitar pro lead on fortnite festival? just setting the controller to rockband guitar and xinput does not work so having an option to "emulate" the riffmaster would be sweet

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
join the discord, people can help you do this.
https://discord.gg/CmdYpXKcEU
