### ISSUE TITLE
[Issue]:  When using drums on PS3 inputs are randomly dropped / not registered

### ISSUE THREAD

**Issue by darkziel** [Santroller/Santroller#17]
I am using a Wii Band Hero Drum Kit connected to a RP, on the guitar configurator I set the output to PS3 and the game recognizes the drums but when hitting the drums sometimes it randomly does not register the input. 
When using the exact same setup on the PC without changing any configuration no inputs are dropped so I think there must be an issue on the PS3 side, do I need to use a specific configuration on the PS3?
Using Wii guitars works fine and I have not had any issues, only the drums are very unreliable when used on the PS3, I used a gamepad tester homebrew on the PS3 and when hitting the pads it randomly registers the DPad right, and sometimes it doesn't register any input at all.

### Version

yes

### What operating system are you using?

Other

### os-other

PS3 FW 4.90

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
