### ISSUE TITLE
[Issue]: USB Adapter maps triggers to the wrong axis when plugged into a PS3

### ISSUE THREAD

**Issue by pajaritia** [Santroller/Santroller#170]
### Please describe your issue.

Using Santroller Configurator v10.1.48
I configured a RP Pico as USB Adapter, plugging a Xbox360 Racing Wheel via USB the inputs look correct on the Santroller Configurator and in Windows.
When connected to a PS3 the triggers (L2 R2) are mapped to the Circle and Triangle buttons pressure sensitive axis.
All the other inputs are correctly mapped and work as expected so I think the adapter is working okay.
![image](https://github.com/Santroller/Santroller/assets/120300340/c4a8827f-a009-426f-b51e-072d77867725)
![20240508_195845](https://github.com/Santroller/Santroller/assets/120300340/c6cacd01-21e0-42ea-838d-591045623fc5)

### Version

v10.1.48

### What operating system are you using?

Windows 10

### os-other

PS3

### What microcontroller are you using?

pi pico

### How is your controller programmed?

other issue not controller related or I have not gotten this far

**Comment by sanjay900** [comment]
Must be something wheels do differently I guess

**Comment by pajaritia** [comment]
I tested with a xbox360 compatible regular gamepad and it's the same issue, triggers are mapped to the pressure of Triangle and Circle.

**Comment by sanjay900** [comment]
can you send me a copy of `%appdata%/SantrollerConfigurator/Santroller/include/config_data.h`
it will only exist after you hit save settings

**Comment by pajaritia** [comment]
[config_data.zip](https://github.com/Santroller/Santroller/files/15257342/config_data.zip)
Here is the file requested, thanks for looking into it.

**Comment by sanjay900** [comment]
Should be fixed with v10.1.49 comes out
