### ISSUE TITLE
[Issue]: Bluetooth Reciever for Guitar Hero Drums registers only 4 lanes on GH 5 Xbox 360

### ISSUE THREAD

**Issue by tloftis** [Santroller/Santroller#172]
### Please describe your issue.

I have a Guitar Hero drum directly wired using the an analog multiplexer and a pico. When plugged in directly via USB, Guitar Hero 5 on 360 shows all 5 lanes with working kick pedal when playing. When connected via a Bluetooth receiver using a secondary RPI Pico it shows only 4 as if a Rockband drum with the kick pedal also no longer registering.

I am fairly sure that I have the configuration correct, shown below.
![image](https://github.com/Santroller/Santroller/assets/8781113/af936fed-4376-4535-82a8-0395cd9eb0d1)

Thank you very much, and the software is awesome

### Version

10.1.50.0

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Fixed by v10.1.63 when it finishes building
