### ISSUE TITLE
[Issue]: Error when i select direct device 

### ISSUE THREAD

**Issue by SyazzZ2009** [Santroller/Santroller#174]
### Please describe your issue.

When I select the input type, no matter which one I select, it only reaches 18% and sends an error later
![Captura de pantalla (122)](https://github.com/Santroller/Santroller/assets/170210136/ce5fc6f7-8421-4521-9b94-de1e2950290b)

### Version

10.1.63.0

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Send the error please.
Also try the portable version as well.

**Comment by sanjay900** [comment]
This may be fixed already, reopen if it isnt.
