### ISSUE TITLE
[Issue]: Missing Kick Pedal input on Blue Tooth Reciever for x-input Bluetooth recievers GH Drums

### ISSUE THREAD

**Issue by tloftis** [Santroller/Santroller#176]
### Please describe your issue.

Pico Bluetooth receivers for Xinput Guitar Hero drums don't receive the Kick pedal input. With wired and bluetooth everything works as expected.

Not great at reading c, but I think the issue is the block below is missing the report out for the "leftShoulder" 'out->leftShoulder |= report->leftShoulder;' in the XBOX360 output_console_type block.
https://github.com/Santroller/Santroller/blob/master/src/shared/main/shared_main.cpp#L836

Thank you very much

### Version

10.1.66.0

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Yeah that looks like it's probably the issue I'll fix it tomorrow

**Comment by sanjay900** [comment]
Im sort of surprised orange isnt missing too, since rightShoulder was also missing
added both in v10.1.67, which is building at the moment
