### ISSUE TITLE
MPR121 is no longer a configurable option

### ISSUE THREAD

**Issue by ZeroOneZero** [Santroller/Santroller#183]
### Please describe your issue.

MPR121 is no longer an option to configure in v10.1.106 and v10.1.107. The last version that allows for the configuration of the touch capacitive sensor is v10.1.105.

### Version

10.1.107

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Hit add setting

**Comment by sanjay900** [comment]
It was getting a bit cluttered with all these options that not everybody was using, so a bunch of stuff got moved to the `add setting` menu
