### ISSUE TITLE
[Issue]: Error when configuring controller

### ISSUE THREAD

**Issue by Grimicka** [Santroller/Santroller#184]
Processing microdetect (platform: atmelavr; board: micro; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/micro.html
PLATFORM: Atmel AVR (5.0.0) > Arduino Micro
HARDWARE: ATMEGA32U4 16MHz, 2.50KB RAM, 28KB Flash
DEBUG: Current (simavr) External (simavr)
PACKAGES: 
 - framework-arduino-avr @ 5.1.0 
 - tool-avrdude @ 1.70200.0 (7.2.0) 
 - toolchain-atmelavr @ 3.70300.220127 (7.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 7 compatible libraries
Scanning dependencies...
Dependency Graph
|-- LUFA
Building in release mode
"C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages/tool-avrdude/avrdude" -C "C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages/tool-avrdude/avrdude.conf" -p atmega32u4 -P COM3 -c avr109 -e
avrdude: AVR device initialized and ready to accept instructions
ignature = 0x1e9587 (probably m32u4)
avrdude: erasing chip
avrdude done.  Thank you.
========================= [SUCCESS] Took 4.48 seconds =========================
Processing sparkfun_promicro (board: sparkfun_promicro16; platform: atmelavr; framework: arduino)
--------------------------------------------------------------------------------
Library Manager: Installing felis/USB-Host-Shield-20 @ ^1.6.0
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: USB-Host-Shield-20@1.6.0 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
Uploading script to detect speed
Processing microdetect (platform: atmelavr; board: micro; framework: arduino)
--------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/micro.html
PLATFORM: Atmel AVR (5.0.0) > Arduino Micro
HARDWARE: ATMEGA32U4 16MHz, 2.50KB RAM, 28KB Flash
DEBUG: Current (simavr) External (simavr)
PACKAGES: 
 - framework-arduino-avr @ 5.1.0 
 - tool-avrdude @ 1.70200.0 (7.2.0) 
 - toolchain-atmelavr @ 3.70300.220127 (7.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 7 compatible libraries
Scanning dependencies...
Dependency Graph
|-- LUFA
Building in release mode
Compiling .pio\build\microdetect\src\avr\lufa\LUFA.c.o
Compiling .pio\build\microdetect\src\avr\lufa\reboot.c.o
Compiling .pio\build\microdetect\src\avr\micro\detect\descriptors_detect.c.o
Compiling .pio\build\microdetect\src\avr\micro\detect\main.c.o
Compiling .pio\build\microdetect\src\avr\micro\shared\bootloader.c.o
Compiling .pio\build\microdetect\libcac\LUFA\LUFACDCSerial.cpp.o
Archiving .pio\build\microdetect\libFrameworkArduinoVariant.a
Compiling .pio\build\microdetect\FrameworkArduino\HardwareSerial.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\HardwareSerial0.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\HardwareSerial1.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\HardwareSerial2.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\HardwareSerial3.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\IPAddress.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\Print.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\Stream.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\Tone.cpp.o
In file included from C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages\framework-arduino-avr\libraries\LUFA/LUFA/LUFA/Drivers/USB/Core/ConfigDescriptors.h:56:0,
                 from C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages\framework-arduino-avr\libraries\LUFA/LUFA/LUFA/Drivers/USB/USB.h:389,
                 from C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages\framework-arduino-avr\libraries\LUFA/LUFA.c.inc:43,
                 from src\avr\lufa\LUFA.c:3:
C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages\framework-arduino-avr\libraries\LUFA/LUFA/LUFA/Drivers/USB/Core/HostStandardReq.h:281:20: warning: 'USB_Host_SendControlRequest_PRV' declared 'static' but never defined [-Wunused-function]
     static uint8_t USB_Host_SendControlRequest_PRV(void* const BufferPtr);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages\framework-arduino-avr\libraries\LUFA/LUFA/LUFA/Drivers/USB/Core/HostStandardReq.h:282:20: warning: 'USB_Host_WaitForIOS' declared 'static' but never defined [-Wunused-function]
     static uint8_t USB_Host_WaitForIOS(const uint8_t WaitType);
                    ^~~~~~~~~~~~~~~~~~~
Compiling .pio\build\microdetect\FrameworkArduino\WInterrupts.c.o
Compiling .pio\build\microdetect\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\WString.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\abi.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\hooks.c.o
Compiling .pio\build\microdetect\FrameworkArduino\main.cpp.o
Archiving .pio\build\microdetect\libcac\libLUFA.a
Compiling .pio\build\microdetect\FrameworkArduino\new.cpp.o
Compiling .pio\build\microdetect\FrameworkArduino\wiring.c.o
Compiling .pio\build\microdetect\FrameworkArduino\wiring_analog.c.o
Compiling .pio\build\microdetect\FrameworkArduino\wiring_digital.c.o
Compiling .pio\build\microdetect\FrameworkArduino\wiring_pulse.S.o
Compiling .pio\build\microdetect\FrameworkArduino\wiring_pulse.c.o
Compiling .pio\build\microdetect\FrameworkArduino\wiring_shift.c.o
Archiving .pio\build\microdetect\libFrameworkArduino.a
Linking .pio\build\microdetect\firmware.elf
Checking size .pio\build\microdetect\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]  10.5% (used 269 bytes from 2560 bytes)
Flash: [=         ]   9.9% (used 2828 bytes from 28672 bytes)
Building .pio\build\microdetect\firmware.hex
Configuring upload protocol...
AVAILABLE: avr109
CURRENT: upload_protocol = avr109
Looking for upload port...
Using manually specified: COM3
Forcing reset using 1200bps open/close on port COM3
Uploading .pio\build\microdetect\firmware.hex
avrdude: AVR device initialized and ready to accept instructions
ignature = 0x1e9587 (probably m32u4)
avrdude: processing -U flash:w:.pio\build\microdetect\firmware.hex:i
avrdude: reading input file .pio\build\microdetect\firmware.hex for flash
         with 2828 bytes in 1 section within [0, 0xb0b]
         using 23 pages and 116 pad bytes
avrdude: writing 2828 bytes flash ...
Writing | ################################################## | 100% 0.22s
avrdude: 2828 bytes of flash written
avrdude: verifying flash memory against .pio\build\microdetect\firmware.hex
Reading | ################################################## | 100% 0.02s
avrdude: 2828 bytes of flash verified
avrdude done.  Thank you.
post_upload(["upload"], [".pio\build\microdetect\firmware.hex"])
========================= [SUCCESS] Took 6.95 seconds =========================
Environment    Status    Duration
-------------  --------  ------------
microdetect    SUCCESS   00:00:06.948
========================= 1 succeeded in 00:00:06.948 =========================
Uploaded, waiting for device to show up
Found rate: 16000000L
Returning to bootloader
[Errno 32] Pipe error
Waiting for bootloader device
CONFIGURATION: https://docs.platformio.org/page/boards/atmelavr/sparkfun_promicro16.html
PLATFORM: Atmel AVR (5.0.0) > SparkFun Pro Micro 5V/16MHz
HARDWARE: ATMEGA32U4 16MHz, 2.50KB RAM, 28KB Flash
DEBUG: Current (simavr) External (simavr)
PACKAGES: 
 - framework-arduino-avr @ 5.1.0 
 - tool-avrdude @ 1.70200.0 (7.2.0) 
 - toolchain-atmelavr @ 3.70300.220127 (7.3.0)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 7 compatible libraries
Scanning dependencies...
Dependency Graph
|-- USB-Host-Shield-20 @ 1.6.0
|-- LUFA
|-- fxpt_math
Building in release mode
Compiling .pio\build\sparkfun_promicro\src\avr\lufa\LUFA.c.o
Compiling .pio\build\sparkfun_promicro\src\avr\lufa\reboot.c.o
Compiling .pio\build\sparkfun_promicro\src\avr\micro\main\main.cpp.o
Compiling .pio\build\sparkfun_promicro\src\avr\micro\shared\bootloader.c.o
Compiling .pio\build\sparkfun_promicro\src\avr\shared\io.cpp.o
Compiling .pio\build\sparkfun_promicro\src\avr\shared\pins.cpp.o
Compiling .pio\build\sparkfun_promicro\src\avr\shared\usb.cpp.o
Compiling .pio\build\sparkfun_promicro\src\shared\config\config.c.o
Compiling .pio\build\sparkfun_promicro\src\shared\controllers\controllers.c.o
Compiling .pio\build\sparkfun_promicro\src\shared\hid\hid.cpp.o
Compiling .pio\build\sparkfun_promicro\src\shared\main\adxl345.cpp.o
Compiling .pio\build\sparkfun_promicro\src\shared\main\i2c_shared.cpp.o
Compiling .pio\build\sparkfun_promicro\src\shared\main\max1704x.cpp.o
Compiling .pio\build\sparkfun_promicro\src\shared\main\mpr121.cpp.o
Compiling .pio\build\sparkfun_promicro\src\shared\main\ps2.cpp.o
Compiling .pio\build\sparkfun_promicro\src\shared\main\ps2_emu.cpp.o
In file included from C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages\framework-arduino-avr\libraries\LUFA/LUFA/LUFA/Drivers/USB/Core/ConfigDescriptors.h:56:0,
                 from C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages\framework-arduino-avr\libraries\LUFA/LUFA/LUFA/Drivers/USB/USB.h:389,
                 from C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages\framework-arduino-avr\libraries\LUFA/LUFA.c.inc:43,
                 from src\avr\lufa\LUFA.c:3:
C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages\framework-arduino-avr\libraries\LUFA/LUFA/LUFA/Drivers/USB/Core/HostStandardReq.h:281:20: warning: 'USB_Host_SendControlRequest_PRV' declared 'static' but never defined [-Wunused-function]
     static uint8_t USB_Host_SendControlRequest_PRV(void* const BufferPtr);
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:\Users\Grim\AppData\Local\SantrollerConfigurator\current\Binaries\platformio\packages\framework-arduino-avr\libraries\LUFA/LUFA/LUFA/Drivers/USB/Core/HostStandardReq.h:282:20: warning: 'USB_Host_WaitForIOS' declared 'static' but never defined [-Wunused-function]
     static uint8_t USB_Host_WaitForIOS(const uint8_t WaitType);
                    ^~~~~~~~~~~~~~~~~~~
Compiling .pio\build\sparkfun_promicro\src\shared\main\shared_main.cpp.o
Compiling .pio\build\sparkfun_promicro\src\shared\main\wii.cpp.o
Compiling .pio\build\sparkfun_promicro\src\shared\main\wii_emu.cpp.o
Compiling .pio\build\sparkfun_promicro\src\shared\usb\descriptors.cpp.o
Compiling .pio\build\sparkfun_promicro\src\shared\usb\string_descriptors.c.o
Compiling .pio\build\sparkfun_promicro\src\shared\usb\xbox.c.o
Compiling .pio\build\sparkfun_promicro\src\shared\usb\xsm3\excrypt_des.c.o
Compiling .pio\build\sparkfun_promicro\src\shared\usb\xsm3\excrypt_parve.c.o
Compiling .pio\build\sparkfun_promicro\src\shared\usb\xsm3\excrypt_sha.c.o
Compiling .pio\build\sparkfun_promicro\src\shared\usb\xsm3\usbdsec.c.o
Compiling .pio\build\sparkfun_promicro\src\shared\usb\xsm3\xsm3.c.o
Compiling .pio\build\sparkfun_promicro\lib71b\SPI\SPI.cpp.o
Compiling .pio\build\sparkfun_promicro\lib511\USB-Host-Shield-20\AMBX.cpp.o
Compiling .pio\build\sparkfun_promicro\lib511\USB-Host-Shield-20\BTD.cpp.o
Compiling .pio\build\sparkfun_promicro\lib511\USB-Host-Shield-20\BTHID.cpp.o
Compiling .pio\build\sparkfun_promicro\lib511\USB-Host-Shield-20\MiniDSP.cpp.o
src\shared\main\shared_main.cpp: In function 'uint8_t tick_inputs(void*, USB_LastReport_Data_t*, uint8_t)':
src\shared\main\shared_main.cpp:1733:10: warning: unused variable 'updateSequence' [-Wunused-variable]
     bool updateSequence = false;
          ^~~~~~~~~~~~~~
src\shared\main\shared_main.cpp: At global scope:
src\shared\main\shared_main.cpp:51:3: warning: 'rtt_t' defined but not used [-Wunused-variable]
 } rtt_t;
   ^~~~~
src\shared\main\shared_main.cpp:40:3: warning: 'ltt_t' defined but not used [-Wunused-variable]
 } ltt_t;
   ^~~~~
src\shared\main\wii_emu.cpp:2:10: fatal error: Wire.h: No such file or directory
**************************************************************
* Looking for Wire.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:Wire.h"
* Web  > https://registry.platformio.org/search?q=header:Wire.h
*
**************************************************************
 #include <Wire.h>
          ^~~~~~~~
compilation terminated.
*** [.pio\build\sparkfun_promicro\src\shared\main\wii_emu.cpp.o] Error 1
========================= [FAILED] Took 28.04 seconds =========================

### Version

10.1.108

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by Grimicka** [comment]
Also, I had this working a few months ago, but changing it to the setting for Fortnite festival started it

**Comment by sanjay900** [comment]
fixed with v10.1.110
