### ISSUE TITLE
[Issue]: Xbox Series S / Fortnite Festival not detecting guitar with Console Binding.

### ISSUE THREAD

**Issue by jorgeramon** [Santroller/Santroller#188]
### Please describe your issue.

Hello, I added the Console Binding for my PS2 guitar (green button). On PC when I plug and press green, it's being detected as keyboard and I can type through the buttons, but when I connect the guitar and press green on Xbox Series S it's not being detected.

I already checked the devices connected on the console but none is shown.

### Version

10.1.141

### What operating system are you using?

Windows 11

### What microcontroller are you using?

arduino pro micro 5V

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Restart the Xbox, few others have said that made it work for them
