### ISSUE TITLE
[Issue]: Invert digital tilt sensor output

### ISSUE THREAD

**Issue by felipefl142** [Santroller/Santroller#19]
### Please describe your issue.

I'm rebuilding a Warrior's of Rock PS3 Guitar w/ a Raspberry Pi Pico clone. I'm using a mercury tilt sensor so I selected digital sensor type. As I was space limited, the behaviour is as follows: on normal position, the sensor stays closed; and when I tilt up, the sensor opens. As such, in my problem we have a normal closed switch.
So, after selecting everything right, looking up on Windows' Controller Configurator, the "Vertical Axis" appears as fully on and when I tilt, the value goes to the middle of the axis bar and as it happens when I play Clone Hero, the star power activates instanly.

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
