### ISSUE TITLE
[Issue]: Analog sticks in Switch console mode don't zero correctly

### ISSUE THREAD

**Issue by Sulfrix** [Santroller/Santroller#191]
### Please describe your issue.

I set up a Pi Pico to use as a USB controller adapter for my Switch. Everything works fine except for the analog sticks. The Switch's calibration screen does not register the analog stick as being properly zeroed, as it displays a ● instead of a ＋. The switch does register a zeroed analog stick whenever i move it slightly down and to the right. This still happens when I unplug my controller from the USB Host input.

### Version

v10.1.151

### What operating system are you using?

Linux

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
I'll try and borrow a switch when I get back from my holiday and I'll take a look

**Comment by sanjay900** [comment]
Fixed with v10.1.200
