### ISSUE TITLE
[Issue]: WS2812 LEDs do not deactivate

### ISSUE THREAD

**Issue by theokrueger** [Santroller/Santroller#198]
### Please describe your issue.

When using WS2812 LEDs, the LEDs do not revert to their initial state after releasing the associated button.

To reproduce:
- Set up WS2812 LED appropriately in the configurator
- Set LED colour to any two values for inactive and active state, and associate a button with it
- Flash the pico

Upon plugging in the controller, the LED will show the correct colour for the inactive state. When pressing the associated button, the LED will change colour correctly to the active state.

However, the LED will remain stuck showing thr active LED colour when the button is released.

Associating multiple button presses with the LED, i.e. green fret and strum, will similarly have the highest priority button colour shown permanently (Strum > green fret).

Controller type and mode seem to have no effect. Tested with HID gamepad, xinput, and keyboard modes.

### Version

Configurator v10.1.153

### What operating system are you using?

Other

### os-other

Linux & Windows

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
I see the issue, I won't be building a new version till I get back from my holiday though.
Everything you need to build yourself is sitting in the following directory when you hit save settings. Feel free to compile that latest commit yourself and see if it's fixed.

Windows: `%appdata%/SantrollerConfigurator/Santroller`
Linux: `~/.config/SantrollerConfigurator/Santroller`
macOS: `/Users/Shared/Library/Application Support/SantrollerConfigurator/Santroller`
