### ISSUE TITLE
Implement Software Auto-Flam for Drums 

### ISSUE THREAD

**Issue by DarkRTA** [Santroller/Santroller#201]
Due to bugs in how Rock Band 3 handles inputs with Pro Drums, some combinations of timings of inputs need to be automatically flammed to avoid issues with inputs being outright dropped by the game.

Currently trying to learn about all cases where this is nessecary, but the biggest one (from a righty perspective) is green pad + green cymbal which is special cased in lefty mode by the engine.

Known Cases:
* Green Pad + Green Cymbal (becomes Green Pad + Red Cymbal in lefty)
* Double Cymbal + Kick (no idea if the kick is needed to cause issues rn)

**Comment by sanjay900** [comment]
Could probably tie the fix into how we handle debounce, where hitting both notes staggers the second one until after the debounce period

**Comment by sanjay900** [comment]
in theory ive implemented flamming for any drum inputs that are hit at the same time in v10.1.216
