### ISSUE TITLE
[Rgression]:  Peripheral APA102 LEDS not working (works on v10.0.211)

### ISSUE THREAD

**Issue by Crafty-The-Fox** [Santroller/Santroller#203]
### Please describe your issue.

trying to do anything related to APA102 leds on peripheral just breaks the entire progam and pressing test LEDs actually crashes it.

works before you added WS2812 support (v10.0.211)

### Version

v10.1.153

### What operating system are you using?

Windows 10

### What microcontroller are you using?

rp2040

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Should be fixed now
