### ISSUE TITLE
[Issue]: Bluetooth Receiver mode

### ISSUE THREAD

**Issue by Vitari-Translates** [Santroller/Santroller#209]
### Please describe your issue.

In bluetooth receiver mode the software wont found any device.

### Version

v10.1.153

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

other issue not controller related or I have not gotten this far

**Comment by UVClay** [comment]
Where did you get your Picos from?

**Comment by Vitari-Translates** [comment]
> Where did you get your Picos from?

From a Hungarian Raspberry Shop.

**Comment by sanjay900** [comment]
When you say the software won't find any device, what do you mean?
Like it's not showing up as something to program in santroller, or the receiver isn't detecting the transmitter

**Comment by Vitari-Translates** [comment]
![Képernyőkép 2024-08-19 211819](https://github.com/user-attachments/assets/19dd5739-926a-4858-bfc7-6635d006117b)
When i press Start Scan not found any device only the the "No Device Found". If I'm guessing correctly, this should work by listing nearby bluetooth devices.

**Comment by sanjay900** [comment]
Specifically, only another pi pico w running the transmitter firmware

**Comment by Vitari-Translates** [comment]
Sorry. Then I seem to have misunderstood its operation. Are there any plans to handle a bluetooth gamepad input?

**Comment by sanjay900** [comment]
Potentially in the future, it'll probably be a while before I get around to that though.

**Comment by sanjay900** [comment]
I am looking into this at the moment. May i ask what kind of controller you were wanting to use?

**Comment by Vitari-Translates** [comment]
Technically all of them. But I know it's not that simple. In the first
round probably the most popular ones like PS4,PS5, Nintendo Switch, XBOX
ONE.

Sanjay Govind ***@***.***> ezt írta (időpont: 2024. szept.
28., Szo, 23:37):

**Comment by Vitari-Translates** [comment]
Technically all of them. But I know it's not that simple. In the first
round probably the most popular ones like PS4,PS5, Nintendo Switch, XBOX
ONE.

**Comment by sanjay900** [comment]
certainly still needs work and i have zero clue what works and doesn't right now, but with the latest release a DS4 in pairing mode will connect as long as you remove bluetooth inputs, add it again and set the mode to classic.
Ill have to figure out how to make it stay connected permanently later.
