### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by BionicPredator** [Santroller/Santroller#211]
### Please describe your issue.

Installed the wii emulation file like it was said to do and when I went to start the game it loaded code and then froze. What went wrong or what did I do wrong? 

### Version

?

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
honestly its all still a work in progress and doesn't really work with every game yet

**Comment by sanjay900** [comment]
Oh by the way, this is all fixed now. The wii emulation stuff is fully stable.
https://github.com/Santroller/santroller-bslug/releases/latest
