### ISSUE TITLE
[Request]: Configuration with multiple types

### ISSUE THREAD

**Issue by XxyZwW** [Santroller/Santroller#214]
### Please describe your request.

Hi, I wanted to know if it is possible to store multiple types in 1 single configuration, I understand that currently there is a way in which you can force a mode by pressing a button before connecting the controller to a console or PC, but my doubt is if in this way you could even force a type, for example pressing START before connecting the controller enters switch controller mode, pressing STRUM BAR before connecting forces the guitar type, pressing SELECT before connecting forces the drum type, etc.

It's just an idea that I don't know if it's possible to implement, this would avoid having to configure the device and depend on a PC every time you want to use it in a different way.
I really appreciate the development and documentation work that is done on the software, it's exceptionally incredible.
Greetings!

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Wii

**Comment by sanjay900** [comment]
Not really possible with the current codebase, I might change things in the future but it's not easy nor will it happen any time soon
