### ISSUE TITLE
[Request]: Support for attaching buttons directly to Pico board to act as a PS2 controller 

### ISSUE THREAD

**Issue by djsedaw** [Santroller/Santroller#216]
### Please describe your request.

Is it possible to attach buttons, joysticks directly to the Pico board and use Santroller to act as a PS2 dualshot controller?

### What operating system are you using?

Linux

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

PS2

**Comment by sanjay900** [comment]
https://santroller.tangentmc.net/wiring_guides/ps2_output.html
