### ISSUE TITLE
[Request]: Add a threshold setting for MIDI Keys Modulation Wheel

### ISSUE THREAD

**Issue by LinosM** [Santroller/Santroller#218]
### Please describe your request.

My Alesis Keytar for example has a tilt function that controls modulation, it'd be cool to set a threshold so it can deploy overdrive at a certain angle instead of at any point.

![gif](https://i.imgur.com/XYjmFQ7.gif)

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

N/A

### How will the microcontroller be programed for this request?

N/A

**Comment by sanjay900** [comment]
How does RB decide what dictates overdrive?

**Comment by LinosM** [comment]
I'm not sure I understand the question.

The Midi Pro Adapter doesn't utilize the modulation wheel at all so there's no way to dictate how it deploys, and the current implementation of the mod wheel in Santroller would just have it deploy whenever the value changes to any number. I'm asking for an optional setting so it doesn't trigger until the value reaches above a user-specified value.

**Comment by sanjay900** [comment]
Oh right yeah, i can add a threshold for sure

**Comment by sanjay900** [comment]
Should be resolved with v10.1.202
