### ISSUE TITLE
[Request]: Make it possible to change pin binding of mosl and sck for leds

### ISSUE THREAD

**Issue by RatInDaHat** [Santroller/Santroller#22]
### Please describe your request.

I'm hoping it would be possible to change the pin binding for sck and mosl for leds. I wired my current board differently than recommended with sck on GPIO 18(pin 24) and mosl on GPIO 19(pin 25). I'm using a rp pi pico. I didn't see where the pin binding is happeneing in your code so here i am asking.  

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
