### ISSUE TITLE
[Request]: RP2350 Support

### ISSUE THREAD

**Issue by sayofthelor** [Santroller/Santroller#220]
### Please describe your request.

as arduino-pico seems to have RP2350 support, i was wondering if this would be coming to santroller? it would be a nice option to reduce board complexity on account of not needing a storage chip with the RP2354. thanks!

### What operating system are you using?

Linux

### os-other

Manjaro Linux

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

N/A

**Comment by sanjay900** [comment]
It's on the list, just need to verify that the erratas don't affect us

**Comment by sanjay900** [comment]
Hopefully implemented in v10.1.209, make sure your pico is in bootloader mode before you try to configure it

**Comment by sayofthelor** [comment]
i got it to flash to my pico 2, i'll solder a usb port onto it tomorrow to see if USB works properly

**Comment by sanjay900** [comment]
Let me know - it wouldn't surprise me if it doesn't

**Comment by sayofthelor** [comment]
hurricane's been hitting my area a bit so i haven't been able to but i should be able to get back to you tomorrow

**Comment by sayofthelor** [comment]
it does work!

![image](https://github.com/user-attachments/assets/5d3bac9a-e1af-42fc-b695-711b3f38c718)

![image](https://github.com/user-attachments/assets/30d8e905-8928-47e9-bc12-781c4e35710a)

**Comment by sanjay900** [comment]
thats fantastic to hear!
