### ISSUE TITLE
[Issue]: commercial license clarification?

### ISSUE THREAD

**Issue by sayofthelor** [Santroller/Santroller#222]
### Please describe your issue.

it is stated in quite a few places santroller isn't allowed to be used commercially, however the main project's license of GPL v3 seems to explicitly permit commercial use. i was just wondering where the line of what can and can't be used commercially is? i'm planning to sell an adapter of my own and regardless of the answer to this i do plan on purchasing a license

### Version

10.1.221

### What operating system are you using?

Windows 10

### os-other

Manjaro Linux

### What microcontroller are you using?

pi pico

### How is your controller programmed?

other issue not controller related or I have not gotten this far

**Comment by sanjay900** [comment]
the firmware is GPL but the tooling isn't, so thats the main problem with not buying a license.
You wouldn't be able to say ship a user a copy of the tool to configure their guitar, though you really don't want to do that anyways as the commercial tooling is much better suited.
