### ISSUE TITLE
[Issue]: Low voltage on MPR121 triggers wrong freets press

### ISSUE THREAD

**Issue by Francisco-Zafra** [Santroller/Santroller#228]
### Please describe your issue.

I have MPR121 setup on my guitar. It gets 3.3v but pin output is only 1.9v. Pressing 3 freets at the same time drops voltage and all freets get triggered. Could it be fixed adding an option to customize MPR121 pressed threshold? I am only using the mpr121 for the freets, no touchbar.

### Version

10.1.263

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
how exactly have you wired this?

**Comment by Francisco-Zafra** [comment]
If i measure voltage on input 3.3 I get 3.3v, its only on the output pins where i get 1.9V and it drops a bit for every freet I press. I have tried to attach an image. Maybe it has something to do with this aliexpress board.
https://es.aliexpress.com/item/1005006196481053.html?spm=a2g0o.order_list.order_list_main.5.21ef194dCxQIhR&gatewayAdapt=glo2esp
![Captura de pantalla 2024-10-14 234848](https://github.com/user-attachments/assets/c9051a6a-9ee3-47e7-a5fb-1c2ea984ab8f)

**Comment by Francisco-Zafra** [comment]
I found out the problem. I was connecting the cables to the touch bar board but that one was not connected to 3.3 so it was draining power, thats why I read 1.9V on MPR121 pins. Connected touch bar board to 3.3 and now works like a charm. You were right, bad wiring... 

Thanks four your help, super great project!
