### ISSUE TITLE
[Request]: Support for Fender Mustang Pro Guitar Controller

### ISSUE THREAD

**Issue by XxyZwW** [Santroller/Santroller#229]
### Please describe your request.

Is it possible to add support for the Rock Band Fender Mustang Pro Guitar Controller for Wii to use on Xbox 360? This has a lot of little buttons all around the neck and strings on the body of the guitar and this comes with a USB dongle like the one on the Rock Band keyboard

I haven't been able to try it yet and I'm really curious to use it, I think this enables pro mode in the Rock Band 3 game.

I see that in the Santroller tool there is no PRO guitar section in any of the menus other than the Fornite Festival section, but I think the gameplay is different.

![image](https://github.com/user-attachments/assets/305dcee5-8169-4746-996a-47a6ccd6dd59)

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Wii

**Comment by sanjay900** [comment]
may work now, haven't got one to test

**Comment by XxyZwW** [comment]
Hello, I tried to program with the latest version, but the tool gets stuck on writing the device.
![Captura de pantalla (1568)](https://github.com/user-attachments/assets/764da9ba-a0df-4275-bb33-f2d49d479364)
![Captura de pantalla (1569)](https://github.com/user-attachments/assets/1f570f94-3d35-4da6-8897-a52f69f3dd45)
Since the "Refresh Device" button does not appear in the main window of the tool, I tried to open an additional window as it was done before to be able to view and use the button, but now I receive the message that there is already a Santroller instance running and it does not open the second window where I could use the button.
![Captura de pantalla (1571)](https://github.com/user-attachments/assets/238d03fb-f750-4b0a-950f-69adc13a67bc)
I also tried to program the device first as a Gamepad to later enter the configuration and change it to the Mustang Pro Guitar, again it got stuck on writing, but once inside the configuration screen the "Refresh Device" button does appear. When I pressed it, it took a while to launch the window to disconnect and reconnect the device and I did so, but it continued to get stuck.
![Captura de pantalla (1572)](https://github.com/user-attachments/assets/6de49097-2909-4a51-bf1e-a10acc966f68)

This is what I was able to try.
I thank you in advance for the attention you give us and the project, you do an extraordinary job.

**Comment by XxyZwW** [comment]
I saw that for the keytar you asked the user to run usb_descriptordumper, would it help if I shared the reading I got when connecting the adapter to the PC?

Information for device Harmonix RB3 Mustang Guitar for Nintendo Wii (VID=0x1BAD PID=0x3430):

------------------------------
Connection Information:
------------------------------
Device current bus speed: FullSpeed
Device supports USB 1.1 specification
Device address: 0x0028
Current configuration value: 0x01
Number of open pipes: 2


------------------------------
Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0110	bcdUSB
0x00	bDeviceClass      
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x08	bMaxPacketSize0   (8 bytes)
0x1BAD	idVendor
0x3430	idProduct
0x0000	bcdDevice
0x01	iManufacturer   "Licensed by Nintendo of America "
0x02	iProduct        "Harmonix RB3 Mustang Guitar for Nintendo Wii"
0x00	iSerialNumber
0x01	bNumConfigurations


-------------------------
Configuration Descriptor:
-------------------------
0x09	bLength
0x02	bDescriptorType
0x0029	wTotalLength   (41 bytes)
0x01	bNumInterfaces
0x01	bConfigurationValue
0x00	iConfiguration
0x80	bmAttributes   (Bus-powered Device)
0x32	bMaxPower      (100 mA)

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x02	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x00	bInterfaceSubClass   
0x00	bInterfaceProtocol   
0x00	iInterface

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0101	bcdHID
0x00	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x0089	bDescriptorLength

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x81	bEndpointAddress  (IN endpoint 1)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x0A	bInterval         (10 frames)

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x02	bEndpointAddress  (OUT endpoint 2)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x01	bInterval         (1 frames)

Microsoft OS Descriptor is not available. Error code: 0x0000001F


--------------------------------
String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  0x0409 
0x01   0x0409  "Licensed by Nintendo of America "
0x02   0x0409  "Harmonix RB3 Mustang Guitar for Nintendo Wii"

------------------------------

Connection path for device: 
Controladora de host USB genérico compatible con xHCI
Root Hub
Concentrador USB genérico
Concentrador USB genérico
Harmonix RB3 Mustang Guitar for Nintendo Wii (VID=0x1BAD PID=0x3430) Port: 1

Running on: Windows 10 or greater (Build Version 22635)

Brought to you by TDD v2.19.0, Dec  5 2023, 12:08:38

**Comment by XxyZwW** [comment]
Indeed, it no longer gets stuck in the process, I was able to program a pi pico device, but when trying to test it, it does detect the pro guitar on Xbox360, but none of the buttons work to move through the menus except for the right pad, which I think is the one assigned to the select button.
I would also like to mention that from Santroler when I configure the USB adapter for the Mustang Pro Guitar, in the "Pro Guitar Inputs" confirmation section no input appears.

![Captura de pantalla (1573)](https://github.com/user-attachments/assets/1dd4259d-e92a-42f5-b7d9-74cbb2389223)


Also, when I try to program with the "Use Passthrough with RPCS3" option disabled, Santroler does not complete the programming, throwing the following error:

> Processing pico (platform: https://github.com/maxgerhardt/platform-raspberrypi/archive/9e55f6db5c56b9867c69fe473f388beea4546672.zip@1.14.0; board: pico; framework: arduino)
> --------------------------------------------------------------------------------
> Verbose mode can be enabled via `-v, --verbose` option
> CONFIGURATION: https://docs.platformio.org/page/boards/raspberrypi/pico.html
> PLATFORM: Raspberry Pi RP2040 (1.14.0) > Raspberry Pi Pico
> HARDWARE: RP2040 133MHz, 256KB RAM, 2MB Flash
> DEBUG: Current (cmsis-dap) External (blackmagic, cmsis-dap, jlink, pico-debug, picoprobe, raspberrypi-swd)
> PACKAGES: 
>  - framework-arduinopico @ 1.40002.0 (4.0.2) 
>  - tool-openocd-rp2040-earlephilhower @ 0.0.0 
>  - tool-openocd-rp2040-earlephilhower @ 0.0.0 
>  - tool-picotool-rp2040-earlephilhower @ 5.120300.240827 (12.3.0) 
>  - toolchain-rp2040-earlephilhower @ 5.120300.240125 (12.3.0)
> Flash size: 2.00MB
> Sketch size: 2.00MB
> Filesystem size: 0.00MB
> Maximium Sketch size: 2093056 EEPROM start: 0x101ff000 Filesystem start: 0x101ff000 Filesystem end: 0x101ff000
> LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
> LDF Modes: Finder ~ chain, Compatibility ~ soft
> Found 67 compatible libraries
> Scanning dependencies...
> Dependency Graph
> |-- USB-Host-Shield-20 @ 1.6.2
> |-- MIDI Library @ 5.0.2
> |-- SPI @ 1.0
> |-- Wire @ 1.0
> |-- fxpt_math
> Building in release mode
> Compiling .pio\build\pico\src\pico\bt.cpp.o
> Compiling .pio\build\pico\src\pico\bt_rx.cpp.o
> Compiling .pio\build\pico\src\pico\bt_rx_cnt.cpp.o
> Compiling .pio\build\pico\src\pico\hidparser.c.o
> Compiling .pio\build\pico\src\pico\io.cpp.o
> Compiling .pio\build\pico\src\pico\main.cpp.o
> Compiling .pio\build\pico\src\pico\pins.cpp.o
> Compiling .pio\build\pico\src\pico\xinput_device.cpp.o
> Compiling .pio\build\pico\src\pico\xinput_host.cpp.o
> Compiling .pio\build\pico\src\shared\config\config.c.o
> Compiling .pio\build\pico\src\shared\controllers\controllers.c.o
> Compiling .pio\build\pico\src\shared\hid\hid.cpp.o
> Compiling .pio\build\pico\src\shared\main\accel.cpp.o
> Compiling .pio\build\pico\src\shared\main\max1704x.cpp.o
> Compiling .pio\build\pico\src\shared\main\mpr121.cpp.o
> Compiling .pio\build\pico\src\shared\main\ps2.cpp.o
> Compiling .pio\build\pico\src\shared\main\ps2_emu.cpp.o
> Compiling .pio\build\pico\src\shared\main\shared_main.cpp.o
> Compiling .pio\build\pico\src\shared\main\wii.cpp.o
> Compiling .pio\build\pico\src\shared\main\wii_emu.cpp.o
> Compiling .pio\build\pico\src\shared\usb\descriptors.cpp.o
> Compiling .pio\build\pico\src\shared\usb\string_descriptors.c.o
> Compiling .pio\build\pico\src\shared\usb\xbox.c.o
> Linking .pio\build\pico\firmware.elf
> Generating UF2 image
> picotool uf2 convert -t elf ".pio\build\pico\firmware.elf" ".pio\build\pico\firmware.uf2"
> Retrieving maximum program size .pio\build\pico\firmware.elf
> Flash size: 2.00MB
> Sketch size: 2.00MB
> Filesystem size: 0.00MB
> Maximium Sketch size: 2093056 EEPROM start: 0x101ff000 Filesystem start: 0x101ff000 Filesystem end: 0x101ff000
> Checking size .pio\build\pico\firmware.elf
> Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
> RAM:   [==        ]  21.3% (used 55956 bytes from 262144 bytes)
> Flash: [=         ]   5.6% (used 116244 bytes from 2093056 bytes)
> Building .pio\build\pico\firmware.bin
> Configuring upload protocol...
> AVAILABLE: blackmagic, cmsis-dap, jlink, mbed, pico-debug, picoprobe, picotool, raspberrypi-swd
> CURRENT: upload_protocol = mbed
> Trying to reset Pico into bootloader mode...
> Looking for upload disk...
> Using manually specified: D:\
> Uploading .pio\build\pico\firmware.bin
> *** [upload] D:\firmware.uf2: Invalid argument
> ========================= [FAILED] Took 12.96 seconds =========================

Anything I can contribute or help with, I'm available.

**Comment by sanjay900** [comment]
Does this work any better with the latest firmwares?

**Comment by XxyZwW** [comment]
No, it keeps giving me an error when I try to program it
I just tried with the latest 10.1.308

![image](https://github.com/user-attachments/assets/186c5e33-fac0-4bdb-9ed5-1982adb0cc3c)

Processing pico (platform: https://github.com/maxgerhardt/platform-raspberrypi/archive/39b90392af50585e429941bd2561a91949a2ba46.zip@1.15.0; board: pico; framework: arduino)
--------------------------------------------------------------------------------
Library Manager: Installing https://github.com/Santroller/USB_Host_Shield_2.0/archive/refs/heads/master.zip @ 1.6.3
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: USB-Host-Shield-20@1.6.3 has been installed!
Library Manager: Installing fortyseveneffects/MIDI Library @ 5.0.2
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: MIDI Library@5.0.2 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/raspberrypi/pico.html
PLATFORM: Raspberry Pi RP2040 (1.15.0) > Raspberry Pi Pico
HARDWARE: RP2040 133MHz, 256KB RAM, 2MB Flash
DEBUG: Current (cmsis-dap) External (blackmagic, cmsis-dap, jlink, pico-debug, picoprobe, raspberrypi-swd)
PACKAGES: 
 - framework-arduinopico @ 1.40400.0 (4.4.0) 
 - tool-openocd-rp2040-earlephilhower @ 0.0.0 
 - tool-openocd-rp2040-earlephilhower @ 0.0.0 
 - tool-picotool-rp2040-earlephilhower @ 5.140200.240929 (14.2.0) 
 - toolchain-rp2040-earlephilhower @ 5.140200.240929 (14.2.0)
Flash size: 2.00MB
Sketch size: 2.00MB
Filesystem size: 0.00MB
PSRAM size: 0.00MB
Maximium Sketch size: 2093056 EEPROM start: 0x101ff000 Filesystem start: 0x101ff000 Filesystem end: 0x101ff000
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 70 compatible libraries
Scanning dependencies...
Dependency Graph
|-- USB-Host-Shield-20 @ 1.6.3
|-- MIDI Library @ 5.0.2
|-- SPI @ 1.0
|-- Wire @ 1.0
|-- fxpt_math
Building in release mode
Compiling .pio\build\pico\FrameworkArduinoBootloader\boot2_w25q080_2_padded_checksum.S.o
Compiling .pio\build\pico\src\pico\bt.cpp.o
Compiling .pio\build\pico\src\pico\bt_rx.cpp.o
Compiling .pio\build\pico\src\pico\bt_rx_cnt.cpp.o
Compiling .pio\build\pico\src\pico\hidparser.c.o
Compiling .pio\build\pico\src\pico\io.cpp.o
Compiling .pio\build\pico\src\pico\main.cpp.o
Compiling .pio\build\pico\src\pico\midi_host.c.o
Compiling .pio\build\pico\src\pico\pins.cpp.o
Compiling .pio\build\pico\src\pico\xinput_device.cpp.o
Compiling .pio\build\pico\src\pico\xinput_host.cpp.o
Compiling .pio\build\pico\src\shared\config\config.c.o
Compiling .pio\build\pico\src\shared\controllers\controllers.c.o
Compiling .pio\build\pico\src\shared\hid\hid.cpp.o
Compiling .pio\build\pico\src\shared\main\accel.cpp.o
Compiling .pio\build\pico\src\shared\main\i2c_shared.cpp.o
Compiling .pio\build\pico\src\shared\main\max1704x.cpp.o
Compiling .pio\build\pico\src\shared\main\mpr121.cpp.o
Compiling .pio\build\pico\src\shared\main\ps2.cpp.o
Compiling .pio\build\pico\src\shared\main\ps2_emu.cpp.o
Compiling .pio\build\pico\src\shared\main\shared_main.cpp.o
Compiling .pio\build\pico\src\shared\main\wii.cpp.o
Compiling .pio\build\pico\src\shared\main\wii_emu.cpp.o
Compiling .pio\build\pico\src\shared\usb\descriptors.cpp.o
Compiling .pio\build\pico\src\shared\usb\string_descriptors.c.o
Compiling .pio\build\pico\src\shared\usb\xbox.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\excrypt_des.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\excrypt_parve.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\excrypt_sha.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\usbdsec.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\xsm3.c.o
Generating linkerscript C:\Users\linke\AppData\Roaming\SantrollerConfigurator\Santroller\.pio\build\pico/memmap_default.ld
Compiling .pio\build\pico\libb46\SPI\SPI.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\AMBX.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\BTD.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\BTHID.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\MiniDSP.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\PS3BT.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\PS3USB.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\PS4Parser.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\PS5Parser.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\PS5Trigger.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\PSBuzz.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\SPP.cpp.o
Archiving .pio\build\pico\libb46\libSPI.a
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\SwitchProParser.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\UHS2_gpio.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\Usb.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\Wii.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\XBOXOLD.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\XBOXONE.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\XBOXONESParser.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\XBOXRECV.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\XBOXUSB.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\adk.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\cdc_XR21B1411.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\cdcacm.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\cdcftdi.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\cdcprolific.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\hidboot.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\hidcomposite.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\hidescriptorparser.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\hiduniversal.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\hidusagetitlearrays.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\masstorage.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\max_LCD.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\message.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\parsetools.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\usbh_midi.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\usbhid.cpp.o
Compiling .pio\build\pico\lib1f9\USB-Host-Shield-20\usbhub.cpp.o
Compiling .pio\build\pico\lib032\MIDI Library\MIDI.cpp.o
Compiling .pio\build\pico\lib044\Wire\Wire.cpp.o
Compiling .pio\build\pico\libe1a\fxpt_math\fxpt_math.c.o
Compiling .pio\build\pico\FrameworkArduino\BluetoothDebug.cpp.o
Compiling .pio\build\pico\FrameworkArduino\Bootsel.cpp.o
Archiving .pio\build\pico\lib032\libMIDI Library.a
Compiling .pio\build\pico\FrameworkArduino\CoreMutex.cpp.o
Compiling .pio\build\pico\FrameworkArduino\FS.cpp.o
Compiling .pio\build\pico\FrameworkArduino\PIOProgram.cpp.o
Archiving .pio\build\pico\lib1f9\libUSB-Host-Shield-20.a
Compiling .pio\build\pico\FrameworkArduino\RP2040Support.cpp.o
Compiling .pio\build\pico\FrameworkArduino\RP2040USB.cpp.o
Compiling .pio\build\pico\FrameworkArduino\Semihosting.cpp.o
Archiving .pio\build\pico\libe1a\libfxpt_math.a
Compiling .pio\build\pico\FrameworkArduino\SerialPIO.cpp.o
Archiving .pio\build\pico\lib044\libWire.a
Compiling .pio\build\pico\FrameworkArduino\SerialUART.cpp.o
Compiling .pio\build\pico\FrameworkArduino\SerialUSB.cpp.o
Compiling .pio\build\pico\FrameworkArduino\StackThunk.cpp.o
Compiling .pio\build\pico\FrameworkArduino\Tone.cpp.o
Compiling .pio\build\pico\FrameworkArduino\WMath.cpp.o
Compiling .pio\build\pico\FrameworkArduino\_freertos.cpp.o
Compiling .pio\build\pico\FrameworkArduino\api\Common.cpp.o
Compiling .pio\build\pico\FrameworkArduino\api\IPAddress.cpp.o
Compiling .pio\build\pico\FrameworkArduino\api\PluggableUSB.cpp.o
Compiling .pio\build\pico\FrameworkArduino\api\Print.cpp.o
Compiling .pio\build\pico\FrameworkArduino\api\Stream.cpp.o
Compiling .pio\build\pico\FrameworkArduino\api\String.cpp.o
Compiling .pio\build\pico\FrameworkArduino\cyw43_wrappers.cpp.o
Compiling .pio\build\pico\FrameworkArduino\delay.cpp.o
Compiling .pio\build\pico\FrameworkArduino\gprof_gmon.c.o
Compiling .pio\build\pico\FrameworkArduino\gprof_shim.S.o
Compiling .pio\build\pico\FrameworkArduino\libb64\cdecode.cpp.o
Compiling .pio\build\pico\FrameworkArduino\libb64\cencode.cpp.o
Compiling .pio\build\pico\FrameworkArduino\lock.cpp.o
Compiling .pio\build\pico\FrameworkArduino\lwip_wrap.cpp.o
Compiling .pio\build\pico\FrameworkArduino\main.cpp.o
Compiling .pio\build\pico\FrameworkArduino\malloc-lock.cpp.o
Compiling .pio\build\pico\FrameworkArduino\posix.cpp.o
Compiling .pio\build\pico\FrameworkArduino\psram.cpp.o
Compiling .pio\build\pico\FrameworkArduino\rp2350-memcpy.S.o
Compiling .pio\build\pico\FrameworkArduino\sdkoverride\btstack_flash_bank.cpp.o
Compiling .pio\build\pico\FrameworkArduino\sdkoverride\inet_chksum.cpp.o
Compiling .pio\build\pico\FrameworkArduino\sdkoverride\newlib_interface.c.o
Compiling .pio\build\pico\FrameworkArduino\sdkoverride\pico_bootsel_via_double_reset.c.o
Compiling .pio\build\pico\FrameworkArduino\stdlib_noniso.cpp.o
Compiling .pio\build\pico\FrameworkArduino\wiring_analog.cpp.o
Compiling .pio\build\pico\FrameworkArduino\wiring_digital.cpp.o
Compiling .pio\build\pico\FrameworkArduino\wiring_private.cpp.o
Compiling .pio\build\pico\FrameworkArduino\wiring_pulse.cpp.o
Compiling .pio\build\pico\FrameworkArduino\wiring_shift.cpp.o
Archiving .pio\build\pico\libFrameworkArduino.a
Linking .pio\build\pico\firmware.elf
Generating UF2 image
picotool uf2 convert -t elf ".pio\build\pico\firmware.elf" ".pio\build\pico\firmware.uf2"
Retrieving maximum program size .pio\build\pico\firmware.elf
Flash size: 2.00MB
Sketch size: 2.00MB
Filesystem size: 0.00MB
PSRAM size: 0.00MB
Maximium Sketch size: 2093056 EEPROM start: 0x101ff000 Filesystem start: 0x101ff000 Filesystem end: 0x101ff000
Checking size .pio\build\pico\firmware.elf
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  21.4% (used 56072 bytes from 262144 bytes)
Flash: [=         ]   5.9% (used 122896 bytes from 2093056 bytes)
Building .pio\build\pico\firmware.bin
Configuring upload protocol...
AVAILABLE: blackmagic, cmsis-dap, jlink, mbed, pico-debug, picoprobe, picotool, raspberrypi-swd
CURRENT: upload_protocol = mbed
Trying to reset Pico into bootloader mode...
Looking for upload disk...
Using manually specified: G:\
Uploading .pio\build\pico\firmware.bin
*** [upload] G:\firmware.uf2: Invalid argument
========================= [FAILED] Took 66.15 seconds =========================

Anything I can contribute or help with, I'm available.

**Comment by sanjay900** [comment]
It feels like there's something odd going on with your pico, it's failing to copy the firmware to it, can you try a different one

**Comment by XxyZwW** [comment]
You were right, I tried with another pico and yes, the programming passed, but when I tried it in operation on Xbox360 or PS3 the buttons don't work, the only thing that works is the directional pad, but it seems to interpret it as if it were the start button
I attach a short video of what it does.

https://github.com/user-attachments/assets/ad4b968f-3a3d-4cff-8905-149a3e76c1e2

Thank you and anything I can contribute or help with, I'm available.

**Comment by sanjay900** [comment]
Save your current configuration using the Save Settings button, and then send the following file:
Windows: %appdata%/SantrollerConfigurator/Santroller/include/config_data.h
Linux: ~/.config/SantrollerConfigurator/Santroller/include/config_data.h
macOS: /Users/Shared/Library/Application Support/SantrollerConfigurator/Santroller/include/config_data.h

**Comment by XxyZwW** [comment]
Sure, when I try to upload the file to GitHub it tells me that format is not allowed, so I compressed it in ZIP

[config_data.zip](https://github.com/user-attachments/files/18249567/config_data.zip)

**Comment by sanjay900** [comment]
In santroller itself what do the inputs you can see look like?

**Comment by XxyZwW** [comment]
Only "Controller Settings", "USB Host Inputs (Detected as PS3 Gamepad)" and "Pro Guitar Inputs", but the latter does not show any input

![Captura de pantalla 2024-12-25 233320](https://github.com/user-attachments/assets/83c4b2c9-b306-4dbd-b0eb-63d048081fed)
![Captura de pantalla 2024-12-25 232741](https://github.com/user-attachments/assets/fb35dc9f-5f57-4fa9-b8c6-fa6e5872dff7)
![Captura de pantalla 2024-12-25 232800](https://github.com/user-attachments/assets/f3cb8bc2-6f75-418d-b3de-0e500dca0c1a)
![Captura de pantalla 2024-12-25 232814](https://github.com/user-attachments/assets/3e21b585-4e46-4023-bd6e-0ec006068dcd)

**Comment by sanjay900** [comment]
oh, that explains it, it really shouldnt detect it as a ps3 gamepad!

**Comment by sanjay900** [comment]
[firmware.uf2.zip](https://github.com/user-attachments/files/18251068/firmware.uf2.zip)
does this make it show up as a ps3 mustang or ps3 squire

**Comment by sanjay900** [comment]
Or just try v10.1.309 when it comes out, it has the changes in it

**Comment by XxyZwW** [comment]
I confirm that it is now correctly detected and works in the game, programmed with version 10.1.311, many thanks, excellent work you do
