### ISSUE TITLE
[Issue]: Guitar Hero Drum

### ISSUE THREAD

**Issue by Psayz** [Santroller/Santroller#230]
### Please describe your issue.

I'm having a problem with my drum, when I hit it once and it seems like an overstrum, it hits several times making the note hit but I lose the count, I'm using a pi pico with a 74hc4067 multiplexer, 3.3v zener diode, resistors 1 megaohm

### Version

Lastest

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Adjust your debounce, thats what its designed to fix

**Comment by Psayz** [comment]
> Ajuste seu debounce, é para isso que ele foi projetado para consertar

I saw this on your website, but where do I find this configuration in santrollerconfig?

**Comment by sanjay900** [comment]
![image](https://github.com/user-attachments/assets/dc16ff07-bbdc-4061-b8ae-e92cf3e07786)

**Comment by Psayz** [comment]
There's no such thing for me

**Comment by sanjay900** [comment]
click where it says controller poll settings to expand it

**Comment by Psayz** [comment]
> click where it says controller poll settings to expand it

![image](https://github.com/user-attachments/assets/0a617a57-bd00-4d67-b2fb-e50a8d5ed2a3)

**Comment by Psayz** [comment]
I reset a pi pico and work!

**Comment by sanjay900** [comment]
Its because you turned on advanced mode, which changes how the debounce stuff works. You don't want advanced mode.
