### ISSUE TITLE
[Issue]: Santroller fails to program Pico Pi

### ISSUE THREAD

**Issue by itsdefter** [Santroller/Santroller#235]
### Please describe your issue.

Processing pico (platform: https://github.com/maxgerhardt/platform-raspberrypi/archive/9e55f6db5c56b9867c69fe473f388beea4546672.zip@1.14.0; board: pico; framework: arduino)
--------------------------------------------------------------------------------
Library Manager: Installing https://github.com/Santroller/USB_Host_Shield_2.0/archive/refs/heads/master.zip @ 1.6.2
Downloading...
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: USB-Host-Shield-20@1.6.2 has been installed!
Library Manager: Installing fortyseveneffects/MIDI Library @ 5.0.2
Downloading 0% 10% 20% 30% 40%
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: MIDI Library@5.0.2 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/raspberrypi/pico.html
PLATFORM: Raspberry Pi RP2040 (1.14.0) > Raspberry Pi Pico
HARDWARE: RP2040 133MHz, 256KB RAM, 2MB Flash
DEBUG: Current (cmsis-dap) External (blackmagic, cmsis-dap, jlink, pico-debug, picoprobe, raspberrypi-swd)
PACKAGES: 
 - framework-arduinopico @ 1.40002.0 (4.0.2) 
 - tool-openocd-rp2040-earlephilhower @ 0.0.0 
 - tool-openocd-rp2040-earlephilhower @ 0.0.0 
 - tool-picotool-rp2040-earlephilhower @ 5.120300.240827 (12.3.0) 
 - toolchain-rp2040-earlephilhower @ 5.120300.240125 (12.3.0)
Flash size: 2.00MB
Sketch size: 2.00MB
Filesystem size: 0.00MB
Maximium Sketch size: 2093056 EEPROM start: 0x101ff000 Filesystem start: 0x101ff000 Filesystem end: 0x101ff000
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 67 compatible libraries
Scanning dependencies...
Dependency Graph
|-- USB-Host-Shield-20 @ 1.6.2
|-- MIDI Library @ 5.0.2
|-- SPI @ 1.0
|-- Wire @ 1.0
|-- fxpt_math
Building in release mode
Compiling .pio\build\pico\FrameworkArduinoBootloader\boot2_w25q080_2_padded_checksum.S.o
Compiling .pio\build\pico\src\pico\bt.cpp.o
Compiling .pio\build\pico\src\pico\bt_rx.cpp.o
Compiling .pio\build\pico\src\pico\bt_rx_cnt.cpp.o
Compiling .pio\build\pico\src\pico\hidparser.c.o
Compiling .pio\build\pico\src\pico\io.cpp.o
Compiling .pio\build\pico\src\pico\main.cpp.o
Compiling .pio\build\pico\src\pico\midi_host.c.o
Compiling .pio\build\pico\src\pico\pins.cpp.o
Compiling .pio\build\pico\src\pico\xinput_device.cpp.o
Compiling .pio\build\pico\src\pico\xinput_host.cpp.o
Compiling .pio\build\pico\src\shared\config\config.c.o
Compiling .pio\build\pico\src\shared\controllers\controllers.c.o
Compiling .pio\build\pico\src\shared\hid\hid.cpp.o
Compiling .pio\build\pico\src\shared\main\accel.cpp.o
Compiling .pio\build\pico\src\shared\main\i2c_shared.cpp.o
Compiling .pio\build\pico\src\shared\main\max1704x.cpp.o
Compiling .pio\build\pico\src\shared\main\mpr121.cpp.o
Compiling .pio\build\pico\src\shared\main\ps2.cpp.o
Compiling .pio\build\pico\src\shared\main\ps2_emu.cpp.o
Compiling .pio\build\pico\src\shared\main\shared_main.cpp.o
Compiling .pio\build\pico\src\shared\main\wii.cpp.o
Compiling .pio\build\pico\src\shared\main\wii_emu.cpp.o
Compiling .pio\build\pico\src\shared\usb\descriptors.cpp.o
Compiling .pio\build\pico\src\shared\usb\string_descriptors.c.o
Compiling .pio\build\pico\src\shared\usb\xbox.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\excrypt_des.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\excrypt_parve.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\excrypt_sha.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\usbdsec.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\xsm3.c.o
Generating linkerscript C:\Users\RTX4090\AppData\Roaming\SantrollerConfigurator\Santroller\.pio\build\pico/memmap_default.ld
Compiling .pio\build\pico\lib426\SPI\SPI.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\AMBX.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\BTD.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\BTHID.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\MiniDSP.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\PS3BT.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\PS3USB.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\PS4Parser.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\PS5Parser.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\PS5Trigger.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\PSBuzz.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\SPP.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\SwitchProParser.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\UHS2_gpio.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\Usb.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\Wii.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\XBOXOLD.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\XBOXONE.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\XBOXONESParser.cpp.o
src\shared\hid\hid.cpp: In function 'uint8_t handle_serial_command(uint8_t, uint16_t, uint8_t*, bool*)':
src\shared\hid\hid.cpp:805:38: error: 'lastSuccessfulWiiPacket' was not declared in this scope; did you mean 'lastSuccessfulGH5Packet'?
  805 |             memcpy(response_buffer, &lastSuccessfulWiiPacket, sizeof(lastSuccessfulWiiPacket));
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~
      |                                      lastSuccessfulGH5Packet
src\shared\hid\hid.cpp:811:38: error: 'lastSuccessfulPS2Packet' was not declared in this scope; did you mean 'lastSuccessfulGH5Packet'?
  811 |             memcpy(response_buffer, &lastSuccessfulPS2Packet, sizeof(lastSuccessfulPS2Packet));
      |                                      ^~~~~~~~~~~~~~~~~~~~~~~
      |                                      lastSuccessfulGH5Packet
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\XBOXRECV.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\XBOXUSB.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\adk.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\cdc_XR21B1411.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\cdcacm.cpp.o
Compiling .pio\build\pico\lib4a2\USB-Host-Shield-20\cdcftdi.cpp.o
*** [.pio\build\pico\src\shared\hid\hid.cpp.o] Error 1
========================== [FAILED] Took 9.59 seconds ==========================

### Version

10.1.282

### What operating system are you using?

Windows 11

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Yeah don't upgrade, githubs being annoying and not letting me upload a
fixed build right now
