### ISSUE TITLE
[Issue]: the miso and mosi selections are swapped 

### ISSUE THREAD

**Issue by djsedaw** [Santroller/Santroller#239]
### Please describe your issue.

When selecting the pins for miso and mosi in the drop down menu, the selections for miso are the mosi pins and vice versa Versa for mosi.

### Version

Latest

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
What exactly are you mapping a mosi and miso pin for?

**Comment by djsedaw** [comment]
im connecting buttons, then joysticks via a multiplexer directly to the pico, then connecting an old ps2 gamepad cable to the mosi, miso, ack ect to the pico, then plugging into the ps2 console

**Comment by sanjay900** [comment]
Then in that case its swapped on purpose. When your plugging it into the PS2, the roles are reversed thus the terminology is swapped and the names are supposed to be swapped around.

**Comment by djsedaw** [comment]
Thank you, didn't know that but now I do!
