### ISSUE TITLE
[Request]: Is this possible to make a drum with a PI PICO?

### ISSUE THREAD

**Issue by Namoku** [Santroller/Santroller#24]
### Please describe your request.

Hello, I tried to make a drum controller with an old RockBand wireless drum I had, but after tried to flash the arduino uno, it doesn't pass 'update needed' in the guitar configurator, so Imma try to make it with a PI PICO, but here's my question, how can I connect the piezoelectric sensors to the board? In the arduino I connected in the analog input using 1M resistor.

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
