### ISSUE TITLE
[Issue]: error programming keytar pro (Raspberry Pi Pico)

### ISSUE THREAD

**Issue by kimo1arquimedes1** [Santroller/Santroller#242]
### Please describe your issue.

When configuring a Raspberry Pi Pico, with the USB host and Pro keyboard combination, it gives the following error, if I remove the USB host the programming ends.

Processing pico (platform: https://github.com/maxgerhardt/platform-raspberrypi/archive/39b90392af50585e429941bd2561a91949a2ba46.zip@1.15.0; board: pico; framework: arduino)
--------------------------------------------------------------------------------
Library Manager: Installing https://github.com/Santroller/USB_Host_Shield_2.0/archive/refs/heads/master.zip @ 1.6.3
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: USB-Host-Shield-20@1.6.3 has been installed!
Library Manager: Installing fortyseveneffects/MIDI Library @ 5.0.2
Unpacking 0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
Library Manager: MIDI Library@5.0.2 has been installed!
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/raspberrypi/pico.html
PLATFORM: Raspberry Pi RP2040 (1.15.0) > Raspberry Pi Pico
HARDWARE: RP2040 133MHz, 256KB RAM, 2MB Flash
DEBUG: Current (cmsis-dap) External (blackmagic, cmsis-dap, jlink, pico-debug, picoprobe, raspberrypi-swd)
PACKAGES: 
 - framework-arduinopico @ 1.40400.0 (4.4.0) 
 - tool-openocd-rp2040-earlephilhower @ 0.0.0 
 - tool-openocd-rp2040-earlephilhower @ 0.0.0 
 - tool-picotool-rp2040-earlephilhower @ 5.140200.240929 (14.2.0) 
 - toolchain-rp2040-earlephilhower @ 5.140200.240929 (14.2.0)
Flash size: 2.00MB
Sketch size: 2.00MB
Filesystem size: 0.00MB
PSRAM size: 0.00MB
Maximium Sketch size: 2093056 EEPROM start: 0x101ff000 Filesystem start: 0x101ff000 Filesystem end: 0x101ff000
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 70 compatible libraries
Scanning dependencies...
Dependency Graph
|-- USB-Host-Shield-20 @ 1.6.3
|-- MIDI Library @ 5.0.2
|-- SPI @ 1.0
|-- Wire @ 1.0
|-- fxpt_math
Building in release mode
Compiling .pio\build\pico\FrameworkArduinoBootloader\boot2_w25q080_2_padded_checksum.S.o
Compiling .pio\build\pico\src\pico\bt.cpp.o
Compiling .pio\build\pico\src\pico\bt_rx.cpp.o
Compiling .pio\build\pico\src\pico\bt_rx_cnt.cpp.o
Compiling .pio\build\pico\src\pico\hidparser.c.o
Compiling .pio\build\pico\src\pico\io.cpp.o
Compiling .pio\build\pico\src\pico\main.cpp.o
Compiling .pio\build\pico\src\pico\midi_host.c.o
Compiling .pio\build\pico\src\pico\pins.cpp.o
Compiling .pio\build\pico\src\pico\xinput_device.cpp.o
Compiling .pio\build\pico\src\pico\xinput_host.cpp.o
Compiling .pio\build\pico\src\shared\config\config.c.o
Compiling .pio\build\pico\src\shared\controllers\controllers.c.o
Compiling .pio\build\pico\src\shared\hid\hid.cpp.o
Compiling .pio\build\pico\src\shared\main\accel.cpp.o
Compiling .pio\build\pico\src\shared\main\i2c_shared.cpp.o
Compiling .pio\build\pico\src\shared\main\max1704x.cpp.o
Compiling .pio\build\pico\src\shared\main\mpr121.cpp.o
Compiling .pio\build\pico\src\shared\main\ps2.cpp.o
Compiling .pio\build\pico\src\shared\main\ps2_emu.cpp.o
Compiling .pio\build\pico\src\shared\main\shared_main.cpp.o
Compiling .pio\build\pico\src\shared\main\wii.cpp.o
Compiling .pio\build\pico\src\shared\main\wii_emu.cpp.o
Compiling .pio\build\pico\src\shared\usb\descriptors.cpp.o
Compiling .pio\build\pico\src\shared\usb\string_descriptors.c.o
Compiling .pio\build\pico\src\shared\usb\xbox.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\excrypt_des.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\excrypt_parve.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\excrypt_sha.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\usbdsec.c.o
Compiling .pio\build\pico\src\shared\usb\xsm3\xsm3.c.o
Generating linkerscript C:\Users\kishi\AppData\Roaming\SantrollerConfigurator\Santroller\.pio\build\pico/memmap_default.ld
Compiling .pio\build\pico\lib9d0\SPI\SPI.cpp.o
Compiling .pio\build\pico\libe59\USB-Host-Shield-20\AMBX.cpp.o
Compiling .pio\build\pico\libe59\USB-Host-Shield-20\BTD.cpp.o
In file included from include/config.h:10,
                 from include/pin_funcs.h:2,
                 from include/shared_main.h:1,
                 from src\shared\main\shared_main.cpp:1:
src\shared\main\shared_main.cpp: In function 'uint8_t tick_inputs(void*, USB_LastReport_Data_t*, uint8_t)':
include/config_data.h:954:24: error: 'struct USB_Host_Data_t' has no member named 'key1'
  954 |     if ((usb_host_data.key1 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2374:9: note: in expansion of macro 'TICK_XBOX_ONE'
 2374 |         TICK_XBOX_ONE;
      |         ^~~~~~~~~~~~~
include/config_data.h:955:46: error: 'struct USB_Host_Data_t' has no member named 'key1'
  955 |         proKeyVelocities[0] = (usb_host_data.key1 << 8);\
      |                                              ^~~~
src\shared\main\shared_main.cpp:2374:9: note: in expansion of macro 'TICK_XBOX_ONE'
 2374 |         TICK_XBOX_ONE;
      |         ^~~~~~~~~~~~~
include/config_data.h:958:24: error: 'struct USB_Host_Data_t' has no member named 'key2'
  958 |     if ((usb_host_data.key2 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2374:9: note: in expansion of macro 'TICK_XBOX_ONE'
 2374 |         TICK_XBOX_ONE;
      |         ^~~~~~~~~~~~~
include/config_data.h:959:46: error: 'struct USB_Host_Data_t' has no member named 'key2'
  959 |         proKeyVelocities[1] = (usb_host_data.key2 << 8);\
      |                                              ^~~~
src\shared\main\shared_main.cpp:2374:9: note: in expansion of macro 'TICK_XBOX_ONE'
 2374 |         TICK_XBOX_ONE;
      |         ^~~~~~~~~~~~~
include/config_data.h:962:24: error: 'struct USB_Host_Data_t' has no member named 'key3'
  962 |     if ((usb_host_data.key3 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2374:9: note: in expansion of macro 'TICK_XBOX_ONE'
 2374 |         TICK_XBOX_ONE;
      |         ^~~~~~~~~~~~~
include/config_data.h:963:46: error: 'struct USB_Host_Data_t' has no member named 'key3'
  963 |         proKeyVelocities[2] = (usb_host_data.key3 << 8);\
      |                                              ^~~~
src\shared\main\shared_main.cpp:2374:9: note: in expansion of macro 'TICK_XBOX_ONE'
 2374 |         TICK_XBOX_ONE;
      |         ^~~~~~~~~~~~~
include/config_data.h:966:24: error: 'struct USB_Host_Data_t' has no member named 'key4'
  966 |     if ((usb_host_data.key4 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2374:9: note: in expansion of macro 'TICK_XBOX_ONE'
 2374 |         TICK_XBOX_ONE;
      |         ^~~~~~~~~~~~~
include/config_data.h:967:46: error: 'struct USB_Host_Data_t' has no member named 'key4'
  967 |         proKeyVelocities[3] = (usb_host_data.key4 << 8);\
      |                                              ^~~~

(Message deleted because it was too long to post.)

include/config_data.h:85:24: error: 'struct USB_Host_Data_t' has no member named 'key2'
   85 |     if ((usb_host_data.key2 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:86:46: error: 'struct USB_Host_Data_t' has no member named 'key2'
   86 |         proKeyVelocities[1] = (usb_host_data.key2 << 8);\
      |                                              ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:89:24: error: 'struct USB_Host_Data_t' has no member named 'key3'
   89 |     if ((usb_host_data.key3 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:90:46: error: 'struct USB_Host_Data_t' has no member named 'key3'
   90 |         proKeyVelocities[2] = (usb_host_data.key3 << 8);\
      |                                              ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:93:24: error: 'struct USB_Host_Data_t' has no member named 'key4'
   93 |     if ((usb_host_data.key4 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:94:46: error: 'struct USB_Host_Data_t' has no member named 'key4'
   94 |         proKeyVelocities[3] = (usb_host_data.key4 << 8);\
      |                                              ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:97:24: error: 'struct USB_Host_Data_t' has no member named 'key5'
   97 |     if ((usb_host_data.key5 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:98:46: error: 'struct USB_Host_Data_t' has no member named 'key5'
   98 |         proKeyVelocities[4] = (usb_host_data.key5 << 8);\
      |                                              ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:101:24: error: 'struct USB_Host_Data_t' has no member named 'key6'
  101 |     if ((usb_host_data.key6 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:102:46: error: 'struct USB_Host_Data_t' has no member named 'key6'
  102 |         proKeyVelocities[5] = (usb_host_data.key6 << 8);\
      |                                              ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:105:24: error: 'struct USB_Host_Data_t' has no member named 'key7'
  105 |     if ((usb_host_data.key7 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:106:46: error: 'struct USB_Host_Data_t' has no member named 'key7'
  106 |         proKeyVelocities[6] = (usb_host_data.key7 << 8);\
      |                                              ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:109:24: error: 'struct USB_Host_Data_t' has no member named 'key8'
  109 |     if ((usb_host_data.key8 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:110:46: error: 'struct USB_Host_Data_t' has no member named 'key8'
  110 |         proKeyVelocities[7] = (usb_host_data.key8 << 8);\
      |                                              ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:113:24: error: 'struct USB_Host_Data_t' has no member named 'key9'
  113 |     if ((usb_host_data.key9 << 8)) {\
      |                        ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:114:46: error: 'struct USB_Host_Data_t' has no member named 'key9'
  114 |         proKeyVelocities[8] = (usb_host_data.key9 << 8);\
      |                                              ^~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:117:24: error: 'struct USB_Host_Data_t' has no member named 'key10'
  117 |     if ((usb_host_data.key10 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:118:46: error: 'struct USB_Host_Data_t' has no member named 'key10'
  118 |         proKeyVelocities[9] = (usb_host_data.key10 << 8);\
      |                                              ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:121:24: error: 'struct USB_Host_Data_t' has no member named 'key11'
  121 |     if ((usb_host_data.key11 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:122:47: error: 'struct USB_Host_Data_t' has no member named 'key11'
  122 |         proKeyVelocities[10] = (usb_host_data.key11 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:125:24: error: 'struct USB_Host_Data_t' has no member named 'key12'
  125 |     if ((usb_host_data.key12 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:126:47: error: 'struct USB_Host_Data_t' has no member named 'key12'
  126 |         proKeyVelocities[11] = (usb_host_data.key12 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:129:24: error: 'struct USB_Host_Data_t' has no member named 'key13'
  129 |     if ((usb_host_data.key13 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:130:47: error: 'struct USB_Host_Data_t' has no member named 'key13'
  130 |         proKeyVelocities[12] = (usb_host_data.key13 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:133:24: error: 'struct USB_Host_Data_t' has no member named 'key14'
  133 |     if ((usb_host_data.key14 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:134:47: error: 'struct USB_Host_Data_t' has no member named 'key14'
  134 |         proKeyVelocities[13] = (usb_host_data.key14 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:137:24: error: 'struct USB_Host_Data_t' has no member named 'key15'
  137 |     if ((usb_host_data.key15 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:138:47: error: 'struct USB_Host_Data_t' has no member named 'key15'
  138 |         proKeyVelocities[14] = (usb_host_data.key15 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:141:24: error: 'struct USB_Host_Data_t' has no member named 'key16'
  141 |     if ((usb_host_data.key16 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:142:47: error: 'struct USB_Host_Data_t' has no member named 'key16'
  142 |         proKeyVelocities[15] = (usb_host_data.key16 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:145:24: error: 'struct USB_Host_Data_t' has no member named 'key17'
  145 |     if ((usb_host_data.key17 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:146:47: error: 'struct USB_Host_Data_t' has no member named 'key17'
  146 |         proKeyVelocities[16] = (usb_host_data.key17 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:149:24: error: 'struct USB_Host_Data_t' has no member named 'key18'
  149 |     if ((usb_host_data.key18 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:150:47: error: 'struct USB_Host_Data_t' has no member named 'key18'
  150 |         proKeyVelocities[17] = (usb_host_data.key18 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:153:24: error: 'struct USB_Host_Data_t' has no member named 'key19'
  153 |     if ((usb_host_data.key19 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:154:47: error: 'struct USB_Host_Data_t' has no member named 'key19'
  154 |         proKeyVelocities[18] = (usb_host_data.key19 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:157:24: error: 'struct USB_Host_Data_t' has no member named 'key20'
  157 |     if ((usb_host_data.key20 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:158:47: error: 'struct USB_Host_Data_t' has no member named 'key20'
  158 |         proKeyVelocities[19] = (usb_host_data.key20 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:161:24: error: 'struct USB_Host_Data_t' has no member named 'key21'
  161 |     if ((usb_host_data.key21 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:162:47: error: 'struct USB_Host_Data_t' has no member named 'key21'
  162 |         proKeyVelocities[20] = (usb_host_data.key21 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:165:24: error: 'struct USB_Host_Data_t' has no member named 'key22'
  165 |     if ((usb_host_data.key22 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:166:47: error: 'struct USB_Host_Data_t' has no member named 'key22'
  166 |         proKeyVelocities[21] = (usb_host_data.key22 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:169:24: error: 'struct USB_Host_Data_t' has no member named 'key23'
  169 |     if ((usb_host_data.key23 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:170:47: error: 'struct USB_Host_Data_t' has no member named 'key23'
  170 |         proKeyVelocities[22] = (usb_host_data.key23 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:173:24: error: 'struct USB_Host_Data_t' has no member named 'key24'
  173 |     if ((usb_host_data.key24 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:174:47: error: 'struct USB_Host_Data_t' has no member named 'key24'
  174 |         proKeyVelocities[23] = (usb_host_data.key24 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:177:24: error: 'struct USB_Host_Data_t' has no member named 'key25'
  177 |     if ((usb_host_data.key25 << 8)) {\
      |                        ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
include/config_data.h:178:47: error: 'struct USB_Host_Data_t' has no member named 'key25'
  178 |         proKeyVelocities[24] = (usb_host_data.key25 << 8);\
      |                                               ^~~~~
src\shared\main\shared_main.cpp:2666:13: note: in expansion of macro 'TICK_PS3'
 2666 |             TICK_PS3;
      |             ^~~~~~~~
Compiling .pio\build\pico\libe59\USB-Host-Shield-20\BTHID.cpp.o
Compiling .pio\build\pico\libe59\USB-Host-Shield-20\MiniDSP.cpp.o
Compiling .pio\build\pico\libe59\USB-Host-Shield-20\PS3BT.cpp.o
*** [.pio\build\pico\src\shared\main\shared_main.cpp.o] Error 1
========================= [FAILED] Took 33.51 seconds =========================

### Version

SantrollerConfigurator v10.1.303

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Was this configuration from an older version of santroller by chance? What happens if you remove the `USB Host Inputs` and then add it back again?

**Comment by kimo1arquimedes1** [comment]
The configuration was done from scratch, and strangely the version I used a long time ago stopped programming the Raspberry Pi Pico, I'm not sure if any cloud file changed or something like that, because before in the old version of Santroller it didn't let me program without wifi, currently I wanted to make some modifications in 2 devices and error in both.
Currently I decided to install the latest version and I was able to program a gamepad even with the USB Host Inputs option.

The error is when wanting to combine USB Host Inputs and the Rock Band Keytar

**Comment by sanjay900** [comment]
Can i get you to try v10.1.305 when it comes out? Do a fresh configuration with that one.

**Comment by kimo1arquimedes1** [comment]
Perfect, now the programming finishes without problems.
Unfortunately there is no option enabled to assign keys, the console detects all the buttons, except the keys.
When I finish programming with Santroller, the keys do not appear to see if they work by default. As you can see in the image, the pad and the normal buttons appear, but the keys do not appear. I have tried with that option and there is no response on any key.
<img width="960" alt="keytar" src="https://github.com/user-attachments/assets/ae73410c-c7fc-4211-9e6e-1dd4737ece83" />

**Comment by sanjay900** [comment]
Save your current configuration using the Save Settings button, and then send the following file:
Windows: %appdata%/SantrollerConfigurator/Santroller/include/config_data.h
Linux: ~/.config/SantrollerConfigurator/Santroller/include/config_data.h
macOS: /Users/Shared/Library/Application Support/SantrollerConfigurator/Santroller/include/config_data.h

**Comment by sanjay900** [comment]
which keyboard are you using?

**Comment by sanjay900** [comment]
Also, try v10.1.307 when it comes out, it should bring all the keys back if you do it with a fresh config and hopefully they will work

**Comment by kimo1arquimedes1** [comment]
Hi, sorry for the delay.

I've already updated, but the keys are not activated according to the number of keys I press, for example key 1 activates key 2, and for example the first 5 activate several keys simultaneously. I tried directly on the console and the same problem. Here I share the configuration and a photo of the device.
![WhatsApp Image 2024-12-23 at 9 35 05 PM](https://github.com/user-attachments/assets/0e8c00bc-2cad-4bc7-92a1-0855aea6365d)

**Comment by kimo1arquimedes1** [comment]
[config.zip](https://github.com/user-attachments/files/18235527/config.zip)
<img width="755" alt="config" src="https://github.com/user-attachments/assets/06e896cd-3963-42d1-b30c-8751125ccdd7" />

**Comment by kimo1arquimedes1** [comment]
Information for device Harmonix RB3 Keyboard for Nintendo Wii (VID=0x1BAD PID=0x3330):

------------------------------
Connection Information:
------------------------------
Device current bus speed: FullSpeed
Device supports USB 1.1 specification
Device address: 0x0003
Current configuration value: 0x01
Number of open pipes: 2


------------------------------
Device Descriptor:
------------------------------
0x12	bLength
0x01	bDescriptorType
0x0110	bcdUSB
0x00	bDeviceClass      
0x00	bDeviceSubClass   
0x00	bDeviceProtocol   
0x08	bMaxPacketSize0   (8 bytes)
0x1BAD	idVendor
0x3330	idProduct
0x0005	bcdDevice
0x01	iManufacturer   "Licensed by Nintendo of America "
0x02	iProduct        "Harmonix RB3 Keyboard for Nintendo Wii"
0x00	iSerialNumber
0x01	bNumConfigurations


-------------------------
Configuration Descriptor:
-------------------------
0x09	bLength
0x02	bDescriptorType
0x0029	wTotalLength   (41 bytes)
0x01	bNumInterfaces
0x01	bConfigurationValue
0x00	iConfiguration
0x80	bmAttributes   (Bus-powered Device)
0x32	bMaxPower      (100 mA)

Interface Descriptor:
------------------------------
0x09	bLength
0x04	bDescriptorType
0x00	bInterfaceNumber
0x00	bAlternateSetting
0x02	bNumEndPoints
0x03	bInterfaceClass      (Human Interface Device Class)
0x00	bInterfaceSubClass   
0x00	bInterfaceProtocol   
0x00	iInterface

HID Descriptor:
------------------------------
0x09	bLength
0x21	bDescriptorType
0x0101	bcdHID
0x00	bCountryCode
0x01	bNumDescriptors
0x22	bDescriptorType   (Report descriptor)
0x0089	bDescriptorLength

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x81	bEndpointAddress  (IN endpoint 1)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x0A	bInterval         (10 frames)

Endpoint Descriptor:
------------------------------
0x07	bLength
0x05	bDescriptorType
0x02	bEndpointAddress  (OUT endpoint 2)
0x03	bmAttributes      (Transfer: Interrupt / Synch: None / Usage: Data)
0x0040	wMaxPacketSize    (1 x 64 bytes)
0x01	bInterval         (1 frames)

Microsoft OS Descriptor is not available. Error code: 0x0000001F


--------------------------------
String Descriptor Table
--------------------------------
Index  LANGID  String
0x00   0x0000  0x0409 
0x01   0x0409  "Licensed by Nintendo of America "
0x02   0x0409  "Harmonix RB3 Keyboard for Nintendo Wii"

------------------------------

Connection path for device: 
Controladora de host USB genérico compatible con xHCI
Root Hub
Concentrador USB genérico
Harmonix RB3 Keyboard for Nintendo Wii (VID=0x1BAD PID=0x3330) Port: 1

Running on: Windows 10 or greater (Build Version 19045)

Brought to you by TDD v2.19.0, Dec  5 2023, 12:08:38

**Comment by sanjay900** [comment]
wrong file, i need config_data.h not config.h

**Comment by sanjay900** [comment]
It will only be there after you hit save settings, if it isnt there that is why

**Comment by kimo1arquimedes1** [comment]
[config_data.zip](https://github.com/user-attachments/files/18235772/config_data.zip)
Sorry, I was using the portable version. I already installed it, here is the file.

**Comment by kimo1arquimedes1** [comment]
[config_data.zip](https://github.com/user-attachments/files/18235778/config_data.zip)

**Comment by sanjay900** [comment]
[firmware.uf2.zip](https://github.com/user-attachments/files/18235788/firmware.uf2.zip)
what happens if you load this firmware onto your pico (either use the reset to arduino button, or hold bootsel while plugging the pico into your computer, then drag the uf2 file onto it)

**Comment by kimo1arquimedes1** [comment]
It works perfectly, I just need to test it on the console. The keys are detected, the touchpad works and the pedal works too (I hope). The only thing that doesn't react is the overload button. I would need to test it in the game, maybe I can check it later. 
The million dollar question, how did you fix it? hehe

**Comment by sanjay900** [comment]
Let me check if i have just missed something for overdrive

**Comment by sanjay900** [comment]
Should all be fixed with v10.1.308

**Comment by kimo1arquimedes1** [comment]
The overdrive button works, I already tested it on the console

**Comment by sanjay900** [comment]
Yeah, v10.1.308 should fix it in the config tool, and brings all the changes from that uf2 file to an actual release

**Comment by kimo1arquimedes1** [comment]
Much appreciated, I hope to one day be able to use the Fender Mustang PRO-Guitar controller. (to be obtained in the future hehe)
