### ISSUE TITLE
[Issue]: can't enter configuration

### ISSUE THREAD

**Issue by Fifroo** [Santroller/Santroller#25]
### Please describe your issue.

i entered the configuration only one time every next time its stuck on flashing, when its finished its automaticly detected as leonardo/pro micro xinput and i cant configure it
![obraz](https://user-images.githubusercontent.com/106787177/234150295-77eb39e2-45d5-4b12-bfb3-74f977b1ac7c.png)

### Version

yes

### What operating system are you using?

Windows 11

### What microcontroller are you using?

arduino pro micro 5V

### How is your controller programmed?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
