### ISSUE TITLE
[Request]: bind multiple pins to a single button

### ISSUE THREAD

**Issue by natalietchi** [Santroller/Santroller#27]
### Please describe your request.

this would be neat - if you could map frets to their respective inputs *and* a strum input it would work similarly to (non-pro) keys, and be compatible with games other than rb3

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
