### ISSUE TITLE
[Request]: Authentication on Xbox 360 without RGH

### ISSUE THREAD

**Issue by CristobalPenaloza** [Santroller/Santroller#29]
### Please describe your request.

Hello! This project is amazing, and I want to direct mod my wii guitars and drums (no plan on going back to wii).

I want to use them on Xbox 360.
But my 360 is a winchester and can't be modded, and I currently have no way of getting another one that is compatible with RGH.

So I'm stuck on the console's controller authentication.
I know that is possible to bypass that authentication using a middleman, like a cronusmax. But that's **extremely** expensive.

Could there be a way to use the very same pico of the guitar to skip the authorization?
Something like, including an extra usb port on the microcontroller to connect an og controller for the authorization. Is a setup like that possible with this firmware?

Thank you so much in advance!

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
