### ISSUE TITLE
[Request]: Pro Micro Analog Pins

### ISSUE THREAD

**Issue by LifeOnAFarm** [Santroller/Santroller#30]
### Please describe your request.

Is there a way to add the option of selecting the analog pins on pins 4 (A6), 6 (A7), 8 (A8), 9 (A9) and10 (A10) to the guitar configurator? It'd be useful for the extra analog pins needed for the drums

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

arduino pro micro 5V

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
