### ISSUE TITLE
[Request]: Add manual delay field

### ISSUE THREAD

**Issue by RE-Gaming** [Santroller/Santroller#34]
I use this for making some Wii guitars work with PS4 Rockband 4. I've noticed the delay between guitars is slightly different (not too much of an issue) but they are noticeably faster than the drum set that I have, by about 30-40ms which is basically impossible to calibrate out in the game. Could a manual delay field be added to the configurator to delay the outputs from being sent to the console. 

My thought would be a user could configure with 0ms delay ideally, then do calibration on game with each device to determine delay differences then reconfigure their devices with a manually added delay per device. 

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Wii

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
