### ISSUE TITLE
[Request]: Support for RB4 Solo Frets

### ISSUE THREAD

**Issue by vcapellan** [Santroller/Santroller#35]
### Please describe your request.

Hello!

I haven't gotten around to modding my guitar yet (my PS4 RB4 Stratocaster is already disassembled and awaiting my pi pico & soldering kit to come in the mail!). However, going through the guides you have and seeing screenshots of the GUI, it looks like there isn't support for the RB4 solo frets. Are there any plans for supporting this in the future?

Thanks for the hard work! 

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
