### ISSUE TITLE
[Issue]: PS2 controller always has some Whammy even when not pressed.

### ISSUE THREAD

**Issue by rwillsuk** [Santroller/Santroller#41]
### Please describe your issue.

Looks like my PS2 SG is showing that there is always some whammy being pressed, even when I'm not pressing it. Not sure if its a guitar issue or an adapter issue (built your adapter with a pico). Would be nice if it could be calibrated.

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

PS2

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
