### ISSUE TITLE
[Request]: Pickup selector

### ISSUE THREAD

**Issue by kizzoknight** [Santroller/Santroller#42]
### Please describe your request.

Could you assign the pickup selector potentiometer to an axis for the rock band guitar so we can set as whatever we want in game

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
