### ISSUE TITLE
[Request]: Pro Drums support for Rock Band

### ISSUE THREAD

**Issue by rjkiv** [Santroller/Santroller#43]
### Please describe your request.

The latest version of the RB Drum configurator tool does not appear to have support for pro drums (i.e. supporting the yellow cymbal, blue cymbal and green cymbal). Adding functionality for these cymbals would be great - thank you for reading this issue and for your hard work on this!

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

arduino micro 5V

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
