### ISSUE TITLE
[Issue]: incorrect Drum mapping 

### ISSUE THREAD

**Issue by JR2703** [Santroller/Santroller#51]
### Please describe your issue.

When having the connectivity type set to Wii and the output to PS3 Guitar hero drums the mapping is incorrect. The yellow cymbal is set to Blue drum & the kick pedal is set to the orange cymbal. 

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

arduino pro micro 5V

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
