### ISSUE TITLE
[Request]: Support for Teensy boards

### ISSUE THREAD

**Issue by y2k04** [Santroller/Santroller#52]
### Please describe your request.

It would make my life a lot easier if this program was compatible with the Teensy. I have the 4.0 version.

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

N/A

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
gonna be honest, i probably won't implement teensy support. Since the firmware is all platform.io based now, it may be possible to implement it but its just not something im interested in doing myself.
