### ISSUE TITLE
[Issue]: Tilt Sensor is incorrect?

### ISSUE THREAD

**Issue by NightmareIris** [Santroller/Santroller#53]
### Please describe your issue.

Unsure if I set my sensor wrong to begin with, but for whatever reason. My tilt is acting similar to an official guitar, in my case an Xplorer, but always triggers starpower on consoles. 

I used SW-520D sensors, which seem to only allow two positions, either on or off. Im guessing this is by design of said switch. But, they never seem to sit at complete 0. It'll sit at its resting angle of -0.00002, which I believe is causing consoles to think its being tilted constantly. Unlike my Xplorer which rests at 0 and goes below that. My sensor is set to "digital". Is this a me issue or the the programs issue?

### Version

yes

### What operating system are you using?

Windows 10

### What microcontroller are you using?

pi pico

### How is your controller programmed?

Wii

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
