### ISSUE TITLE
[Request]: Player 1-4 Led support

### ISSUE THREAD

**Issue by gitmesomepizza** [Santroller/Santroller#57]
### Please describe your request.

I would like to restore the ability to use the LEDs that are pre-built into some guitars to indicate if a guitar is player/controller 1, 2, 3, or 4.
Xbox guitars had the Xbox 4 LED ring, PlayStation had the 4 red LEDs. Those LEDs should already be rated around 3v.

Also, thank you for making this awesome tool!

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
