### ISSUE TITLE
[Request]: Bind a button to multiple pins

### ISSUE THREAD

**Issue by stevenla** [Santroller/Santroller#58]
### Please describe your request.

Sometimes tilt activation is hard to set up properly (e.g. RPCSX3 Rock Band is kind of finicky), so it'd be nice to be able to bind digital tilt pin to select IN ADDITION to having the select button already bound to a pin. Kind of like the inverse of sanjay900/Santroller#81. This would be a lot easier for users than opening the controller up and shorting tilt to select.

### What operating system are you using?

Windows 11

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Direct

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
