### ISSUE TITLE
[Request]: Option to calibrate Whammy Bar on a Wii connectivity

### ISSUE THREAD

**Issue by MrLuigi002** [Santroller/Santroller#59]
### Please describe your request.

I transformed a Wiitar to a XInput guitar using your guide and a Raspberry Pi Pico a couple of days ago, and I've been testing it on a Xbox 360 using InvoxiPlayGames' UsbdSecPatch, which works perfectly. But I discovered that my guitar has a slight drift in the Whammy Bar, making it detected as slightly pressed all the time.

Some Guitar Hero games let you calibrate the Whammy, but others like Van Halen don't. So would it be possible to add it as an option in the GuitarConfigurator? I see you can do it if you do a Direct wiring, but not on a Wii or PS2 connection.

### What operating system are you using?

Windows 10

### What microcontroller are you making a request for?

pi pico

### How will the microcontroller be programed for this request?

Wii

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
