### ISSUE TITLE
Pro Micro 5V takes approx 40 seconds to detect in Windows 10 when configured as Xinput Guitar Hero Guitar - Direct

### ISSUE THREAD

**Issue by puredave** [Santroller/Santroller#86]
Using latest version and configuring as a Direct Xinput Guitar Hero Guitar controller. Whenever the pro micro (5V) is connected to USB it will take about 40 seconds to finish adding the controller to Windows. It also seems to hang the entire system during this time. This occurs on a Windows 10 Dell Laptop (Intel CPU)  and my main Clone Hero PC (AMD Ryzen 1600 also Windows10). 

I tested it with 2 of my Windows 11 PCs and the issue is non-existent and there is no problem. 

If I configure it as a Direct PS3 Guitar Hero Guitar controller this issue does not occur on Windows 10 and it connects to USB and is ready to go instantly. All well and good but I don't particularly want to configure it as a PS3 controller ;)

Tried with version 8.4.5 and same issue.

Is this a known issue with Pro Micro 5V & Windows 10 (when configured as a Direct - Xinput Guitar) and is there a work around/bug fix or is there something strange afoot at the circle-K?

**Comment by sanjay900** [comment]
Fixed by [new firmware](https://github.com/Santroller/Santroller/releases/tag/v10.0.1)
